### ISSUE TITLE
expose dialog-confirm / dialog-dismiss styling through css vars

### ISSUE THREAD

**Issue by liebrand** [PolymerElements/paper-dialog#10]
The confirm and dismiss buttons on a dialog can not be themed right now (without using /deep/). It would be good if the dialog would expose at least the color and background for these buttons to theme them. (or perhaps even better, expose css mixins)

**Comment by morethanreal** [comment]
The buttons are provided as light DOM of the `<paper-dialog>`, so they should be style-able by the user. For example:

``` html
<style is="custom-style">
  paper-button[dialog-confirm] {
    background: green;
  }
  paper-button[dialog-dismiss] {
    background: red;
  }
</style>

<paper-dialog>
  <div class="buttons">
    <paper-button dialog-dismiss>Cancel</paper-button>
    <paper-button dialog-confirm>OK</paper-button>
  </div>
</paper-dialog>
```

**Comment by liebrand** [comment]
Ah, but if I use the dialog in the local dom of other (my) custom elements, then i'd have to use /deep/ should I not?

I thought using css vars was really the recommended way to get styling or rather theme'ing done?

**Comment by morethanreal** [comment]
If it's in the local dom, you could style it in the element stylesheet and optionally provide your own hook if you need it style it from outside of that:

``` html
<dom-module id="my-element">
  <style is="custom-style">
    paper-button[dialog-confirm] {
      background: green;
      @apply(--my-element-dialog-confirm-button); /* outer scope can define this mixin */
    }
    paper-button[dialog-dismiss] {
      background: red;
      @apply(--my-element-dialog-dismiss-button); /* outer scope can define this mixin */
    }
  </style>
  <template>
    <paper-dialog>
      <div class="buttons">
        <paper-button dialog-dismiss>Cancel</paper-button>
        <paper-button dialog-confirm>OK</paper-button>
      </div>
    </paper-dialog>
  </template>
</dom-module>
```

**Comment by notwaldorf** [comment]
@liebrand Does Yvonne's solution work? Please re-open if it doesn't. Thanks!
