### ISSUE TITLE
paper-dialog[modal] disables ESC

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/paper-dialog#102]
### Description

paper-dialog[modal] disables escape key
### Expected outcome

paper-dialog[modal] would allow escape key to close the dialog
### Actual outcome

according to the documentation, paper-dialog[modal] sets noCancelOnEsc to true

[The ARIA spec on modals mentions that ESC should close the modal](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal).

> Escape - There should be a method to close the dialog without taking any action. This could be implemented via a cancel button which is keyboard accessible. It is recommended that a dialog also be cancelled by pressing the Escape key with focus on any item.

**Comment by valdrinkoshi** [comment]
Hi @robdodson, PTAL at this issue https://github.com/PolymerElements/paper-dialog-behavior/issues/79
Closing as it's a duplicate

**Comment by robdodson** [comment]
I tried to read through the comments on https://github.com/PolymerElements/paper-dialog-behavior/issues/64 but they only show comments made by @valdrinkoshi and not the other folks in the thread so it's hard to figure out why the decision was made to force escape to not close the modal. It seems like following the ARIA spec would be the right course of action, no?

**Comment by valdrinkoshi** [comment]
Hi @robdodson, so this was the original issue/feature request https://github.com/PolymerElements/paper-dialog/issues/27

Currently, `modal` sets `withBackdrop, noCancelOnEscKey, noCancelOnOutsideClick` mainly for UX coherency (as mentioned in the original issue):

> From a UX perspective, the esc key and clicking outside is about the same. Either they're both allowed, or they're both disabled. 

`modal` should prevent the "accidental" closing of the dialog (e.g. click outside, click `esc` key) unless explicitly done by clicking on a dedicated ui element (e.g. button). 
In terms of a11y, the dismiss button can be reached by moving the focus via `tab` key.
Also, this is very application specific, e.g. if I want to show a modal dialog showing terms and conditions & I want my user to either accept or decline them, I don't want to allow him to press `esc` & "get away with it" :p

FYI @alice, WDYT?

**Comment by alice** [comment]
I agree that `noCancelOnEscKey` and `noCancelOnOutsideClick` seem more or less equivalent (should possibly be bundled together as something like `noImplicitCancel`?)

I'm not sure about `modal` implying that bundled concept, though. I think there are two "flavours" of `modal` which you see in the wild:
- the "lightbox" style UI on e.g. chrome://settings/createProfile (that actually does have the same behaviour as the original issue mentioned, where escape works but clicking outside the dialog doesn't), which doesn't imply a user _must_ take an action, only that they _can_;
- a more aggressive "prompt" like you mention, which _must_ be interacted with before the UI flow can continue. In this case, the user needs to take an explicit action within the dialog.

It seems like we should be able to have both be considered `modal`, and whatever we decide the default should be, the bundled `[no]implicitCancel` property should default to `false` - i.e. if the "lightbox" style should be the default, then `noImplicitCancel` would be a sensible property name, and default to false; conversely if "prompt" is the right default behaviour then `implicitCancel` would make more sense.

In either case, though, the other modal implications (effectively making the rest of the page `inert` and showing a backdrop to visually convey that behaviour) should hold. Conversely, a _non-modal_ dialog should always stick around until explicitly dismissed.

**Comment by valdrinkoshi** [comment]
The `withBackdrop` property addresses exactly the common point of the 2 examples you made: it makes the rest of the page inert and shows a backdrop to visually convey the behavior.
The Polymer user is free to use any permutation of the properties `withBackdrop, noCancelOnEscKey, noCancelOnOutsideClick` to achieve the desired UX.
 `paper-dialog` currently offers `modal` as a shortcut to set `withBackdrop, noCancelOnEscKey, noCancelOnOutsideClick` in one shot. The point of discussion seems to be: should `modal` also set `noCancelOnEscKey`? 
I'm fine with either way, I see valid reasons to both set it or not, but this depends on the application requirements, and I believe a11y for this follows accordingly.

**Comment by robdodson** [comment]
I think we can close this. It's probably not worth changing the API again so soon after the previous change and developers can set the attributes they need to get the modal behavior they expect.
