### ISSUE TITLE
iron-overlay-closed documentation error

### ISSUE THREAD

**Issue by panuhorsmalahti** [PolymerElements/paper-dialog#103]
### Description

The documentation specifies that the event for iron-overlay-closed contains a closingReason attribute (or is that supposed to be the name of the callback parameter?). However, the correct attribute is `detail`, which contains the `canceled` attribute.

Might be a good idea to also document the `confirmed` attribute.
### Steps to reproduce
1. Put a `paper-dialog` element in the page with cancel/ok buttons as per the demo example
2. Open the dialog
3. Click the `OK` button.
### Browsers Affected
- [X] Chrome

**Comment by valdrinkoshi** [comment]
This needs to be fixed in `iron-overlay-behavior`.
About the documentation of `confirmed`, I've created a separate issue in `paper-dialog-behavior`: https://github.com/PolymerElements/paper-dialog-behavior/issues/89

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/iron-overlay-behavior#163
