### ISSUE TITLE
Dialog not positioned correctly in ios device

### ISSUE THREAD

**Issue by marxtseng** [PolymerElements/paper-dialog#106]
[Screenshot](https://goo.gl/photos/mdyGnP6hpQCnYdeL6)

**Comment by valdrinkoshi** [comment]
FYI https://github.com/PolymerElements/paper-dialog/blob/master/CONTRIBUTING.md#filing-issues

This seems similar to https://github.com/PolymerElements/paper-dialog/issues/105.

**Comment by valdrinkoshi** [comment]
Closing since pending response since 8 days and looks very similar to #105.
