### ISSUE TITLE
paper-dialog-scrollable automatically scrolls to top when the content changes

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-dialog#107]
`paper-dialog-scrollable` scrolls automatically to top when the content changes. I think this is an unwanted behavior. Here there is an example: scroll all down and click on the last item (Item 8):
http://jsbin.com/nuyeyotoma/edit?html,output

_Copied from original issue: [PolymerElements/paper-dialog-behavior/issues/73](https://github.com/PolymerElements/paper-dialog-behavior/issues/73)_

**Comment by valdrinkoshi** [comment]
Closing as duplicate of https://github.com/PolymerElements/paper-dialog-behavior/issues/73.
