### ISSUE TITLE
draggable dialog

### ISSUE THREAD

**Issue by J3remyD** [PolymerElements/paper-dialog#108]
It could be cool to have a draggable dialog : you just add an attribute draggable or something, and you can dragg and drop your dialog somewhere on the screen.
Like, I have this use case that has a modal over a view, that's handling filtering, and users can't see that the filtering changes are applied real-time to the view, so that'd be cool to have it handled by the component itself instead of doing the logic on my side, to be able to move it somewhere on the screen, or dock it ? I don't know...

What do you think of it as an enhancement? Or is it already done and I'm missing something ?

Thanks,
Jeremy

**Comment by valdrinkoshi** [comment]
Hi @J3remyD, looks like a cool enhancement, but I'd rather do a new behavior for this (e.g. `MyDraggableBehavior`), and let the element author decide if to opt in or not, e.g.

``` javascript
Polymer({
  is: 'my-dialog',
  behaviors: [
    Polymer.PaperDialogBehavior, 
    MyDraggableBehavior
  ],
  ...
});
```

`paper-dialog-behavior` implements `iron-overlay-behavior`, which implements `iron-fit-behavior` (responsible for positioning/centering of the element). If the element is already positioned, `iron-fit-behavior` won't center it anymore.

**Comment by valdrinkoshi** [comment]
Closing this as won't be a property of `paper-dialog` but rather a separate opt-in behavior, we can keep discussing in here though :)
