### ISSUE TITLE
Get invalid ARIA attribute Error when running a11ySuite

### ISSUE THREAD

**Issue by liwei918** [PolymerElements/paper-dialog#110]
When I add following code, I got error when I try to test it using a11ySuite.   I am using chrome.
 <paper-dialog id="confirmModal" modal>
      <div>Are you sure?</div>
      <div class="buttons">
        <paper-button dialog-dismiss>Cancel</paper-button>
        <paper-button dialog-confirm>Confirm</paper-button>
      </div>
    </paper-dialog>

Here is the error message:
This element has an invalid ARIA attribute

Error: Warning: AX_ARIA_11 (This element has an invalid ARIA attribute) failed on the following element:
# confirmModal

See https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_aria_11 for more information.
  Context.<anonymous> at /components/web-component-tester/data/a11ySuite.js:66

**Comment by valdrinkoshi** [comment]
Hi @liwei918, we can't see the code. Could you share how you're using a11ySuite?

**Comment by liwei918** [comment]
Hi,
my test code here:<html>  <head>    <meta charset="utf-8">    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">
    <script src="../../webcomponentsjs/webcomponents-lite.js"></script>    <script src="../../web-component-tester/browser.js"></script>    <script src="../../test-fixture/test-fixture-mocha.js"></script>
        <link rel="import" href="../test-polymer-dialog.html">  </head>  <body>
        <test-fixture id="basic">      <template>        <test-polymer-dialog></test-polymer-dialog>      </template>    </test-fixture>
    <script>
          var myEl;      //var ignoreRules = ['badAriaAttribute'];      var ignoreRules = [];
      suite('<gm-maven-reservation-page>', function() {        setup(function() {          myEl = fixture("basic");        });
        test("existing", function() {          expect(myEl).to.be.ok;        });
        a11ySuite('basic',ignoreRules);
      });
    </script>
  </body></html>------------------------------------------------------------------------------------------------my dialog cod is here this:
      <paper-dialog id="confirmModal" modal>        <div>Are you sure?</div>        <div class="buttons">          <paper-button dialog-dismiss>Cancel</paper-button>          <paper-button dialog-confirm on-tap="_launchAdminTool">Confirm</paper-button>        </div>      </paper-dialog> 

```
On Monday, June 6, 2016 1:28 PM, Valdrin Koshi <notifications@github.com> wrote:
```

 Hi @liwei918, we can't see the code. Could you share how you're using a11ySuite?—

**Comment by valdrinkoshi** [comment]
Hi @liwei918, I don't see the test failing http://jsbin.com/bedesu/1/edit?html,output
Could you modify the jsbin to show the failure?
![no-fail](https://cloud.githubusercontent.com/assets/6173664/15982411/4a1b55d4-2f3b-11e6-98c3-416ace9c8492.gif)

**Comment by liwei918** [comment]
Hi,
If I do the same thing like yours which is put into one file without link and import polymer...,  there is no error. But the test stops after the second test case:   
- basic-test.html
  - <test-polymer-dialog>
    -   
      existing0ms‣
  - A11y Audit - Fixture: basic
  - This element does not support ARIA roles, states and properties0ms‣
  - Meaningful images should not be used in element backgrounds0ms‣

When I use two files which seperates the polymer element as one html file like this.
<link rel="import" href="../polymer/polymer.html"><link rel="import" href="../paper-dialog/paper-dialog.html">
<dom-module id="test-polymer-dialog">
  <template>
    <h1>&lt;test-polymer-dialog&gt;</h1>
    <paper-dialog id="confirmModal" modal>      <div>Are you sure?</div>      <div class="buttons">        <paper-button dialog-dismiss>Cancel</paper-button>        <paper-button dialog-confirm on-tap="_launchAdminTool">Confirm</paper-button>      </div>    </paper-dialog>  </template>
</dom-module>

<script>  (function() {    'use strict';
    Polymer({
      is: 'test-polymer-dialog',
      _launchAdminTool: function() {        window.open('about:blank', '_blank');      }
    });  })();
</script>

The test result has 7 more test cases, it continues after display the errors:
- <test-polymer-dialog>
  -   
    existing0ms‣
- A11y Audit - Fixture: basic
  - This element does not support ARIA roles, states and properties0ms‣
  - Elements with ARIA roles must be in the correct scope0ms‣
  - This element has an invalid ARIA attribute‣
    Error: Warning: AX_ARIA_11 (This element has an invalid ARIA attribute) failed on the following element:
    #confirmModal
    See https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_aria_11 for more information.
    Context.<anonymous> at /components/web-component-tester/data/a11ySuite.js:66
    -   
      This element has an invalid ARIA attribute‣
      Error: Warning: AX_ARIA_11 (This element has an invalid ARIA attribute) failed on the following element:
      #confirmModal
      See https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_aria_11 for more information.
      Context.<anonymous> at /components/web-component-tester/data/a11ySuite.js:66
    -   
      ARIA state and property values must be valid0ms‣
  - Elements with ARIA roles must use a valid, non-abstract ARIA role0ms‣
  - Text elements should have a reasonable contrast ratio0ms‣
  - Meaningful images should not be used in element backgrounds0ms‣
  - Elements with ARIA roles must have all required attributes for that role0ms‣
  - Avoid positive integer values for tabIndex0ms‣
  - This element has an unsupported ARIA attribute0ms
  
  On Friday, June 10, 2016 9:37 PM, Valdrin Koshi notifications@github.com wrote:
  
  Hi @liwei918, I don't see the test failing http://jsbin.com/bedesu/1/edit?html,output
  Could you modify the jsbin to show the failure?—

**Comment by sasivarnan** [comment]
On `paper-dialog`, the `aria-modal` attribute is set by the `paper-dialog-behavior`. The `aria-modal` attribute is not defined by W3C Recommendation (https://www.w3.org/TR/wai-aria/states_and_properties#state_prop_def).

Only the attributes defined by W3C Recommendation are considered as valid and hence causing the an invalid ARIA attribute error.

A quick workaround for fixing this is to remove the `aria-modal` attribute explicitly in the attached function of the parent component contains the `paper-dialog` element

```
this.$.dialog.removeAttribute('aria-modal');
```

**Comment by valdrinkoshi** [comment]
@liwei918 could you confirm that the fix suggested by @sasivarnan works for you? `this.$.dialog.removeAttribute('aria-modal');`

Concerning the `aria-modal` attribute, @sasivarnan is right, it is not a valid aria attribute. 
It was added in `paper-dialog-behavior` from this PR https://github.com/PolymerElements/paper-dialog-behavior/pull/4, @cdata and @notwaldorf reviewed it so they might have more insights on why it was added and if it is needed (we have checks for its existence also in the unit tests).

**Comment by liwei918** [comment]
Hi,
I got  following error: Uncaught console.error: Error stamping [object HTMLTemplateElement] TypeError: Cannot read property 'removeAttribute' of undefined
I add following code in my element file:      ready: function() {        this.$.dialog.removeAttribute('aria-modal');      }
I am not sure if that is the right code through.
Thanks,Li 
extend.js:15

```
On Friday, June 24, 2016 10:00 AM, Valdrin Koshi <notifications@github.com> wrote:
```

 @liwei918 could you confirm that the fix suggested by @sasivarnan works for you? this.$.dialog.removeAttribute('aria-modal');Concerning the aria-modal attribute, @sasivarnan is right, it is not a valid aria attribute. 
It was added in paper-dialog-behavior from this PR PolymerElements/paper-dialog-behavior#4, @cdata/@notwaldorf reviewed it so they might have more insights on why it was added and if it is needed (we have that also in the unit tests).—

**Comment by sasivarnan** [comment]
@liwei918 Do you set the id attribute as `dialog` to your `paper-dialog`?

```
<paper-dialog id="dialog"></paper-dialog>
```

**Comment by liwei918** [comment]
After I change the id , test has passed.
Thanks.Li 

```
On Monday, June 27, 2016 11:06 AM, Sasivarnan R <notifications@github.com> wrote:
```

 @liwei918 Do you set the id attribute as dialog to your paper-dialog?<paper-dialog id="dialog"></paper-dialog>

**Comment by valdrinkoshi** [comment]
Cool! Will move this issue to the right repository. 
`aria-modal` is not a valid attribute and should not be added by `paper-dialog-behavior`.

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/paper-dialog-behavior#95
