### ISSUE TITLE
positionTarget and horizontal/vertical align example

### ISSUE THREAD

**Issue by xwsxethan** [PolymerElements/paper-dialog#111]
### Description

This isn't so much an issue as just a request for more documentation. I'm having trouble being able to use positionTarget and the horizontal/vertical align properties to actually align my dialog to another element. An example of this would be amazing since the properties and position functions are all present in the API, but not used in the example for actually positioning a dialog (seems to be done via CSS).

The specific case I want to use this for is as follows: I have a button (in a completely separate part of the DOM from my dialog) as a child element of a paper-header-panel. I want this dialog to open when the button is clicked and be positioned underneath (in the y-axis sense) the button to make it appear somewhat like a dropdown. I can't use a dropdown or dialog within the same DOM as the button itself because the parent paper-header-panel causes the dialog to be rendered behind other elements. I'm hoping just having a reference to the button to find the element will suffice along with some simple alignment rather than doing this all through CSS, but I can't get it to work.
### Expected outcome

Demo provides clear example of positioning the paper-dialog relative to another element using positionTarget, horizontalAlign, verticalAlign, possibly the offsets, and if necessary the position function.
### Actual outcome

I have no idea how to use these properties and have attempted several variations with no success. Doesn't seem like many others are using this either from cursory searches.
### Live Demo

NA
### Steps to reproduce
1. Attempt to position a paper-dialog element using Polymer properties and no CSS.
2. Fail repeatedly.
3. Lie down.
4. Try not to cry.
5. Cry a lot.
### Browsers Affected

NA

If it's not obvious, some of this is meant to be humorous, but I do sincerely appreciate any help you can provide with using what you've already developed. Thanks for taking the time to read this!

**Comment by thexs-dev** [comment]
Any hint or workaround?
I have been fighting to position a dialog, based on the button who called it, with no success so far

**Comment by xwsxethan** [comment]
If you're doing this dynamically in Javascript, you can get the button element and walk from it up to the top level of your DOM through the parentElement property, getting the various height, width, and offset properties you need and calculating at each level. From there, you can determine exactly the position and bounding box of your button. If you know the size and offset you want for your dialog, then you can use that and the button's position and bounding box in order to determine the dialog's x and y coordinates then place it as appropriate.

It's really quite awful though, and you'll also need to hook into page resize and other such events to resize or move the dialog as appropriate if your button moves, for example by shrinking the window or flipping a phone to portrait from landscape.

**Comment by valdrinkoshi** [comment]
@xwsxethan @Fausto-theXS it should be enough to set the `positionTarget`, see here http://jsbin.com/dusewev/1/edit?html,output

**Comment by thexs-dev** [comment]
Thanks !!!! @valdrinkoshi 
I knew it had to be trivial, because those are the most difficult tasks
I spent more than a few hours
You saved my day !!

p.s. I had to update to version 1.5.0 for this to work

**Comment by xwsxethan** [comment]
+1 to what @Fausto-theXS said. Will #112  be live on [here](https://elements.polymer-project.org/elements/paper-dialog?view=demo:demo/index.html&active=paper-dialog) soon?

**Comment by valdrinkoshi** [comment]
Happy to see it helped :)
It will be live as soon as it gets reviewed by @notwaldorf & merged, then I'll release a new version of `paper-dialog` and we'll publish it in the catalog. Stay tuned!
