### ISSUE TITLE
focus via tab problem with dynamic disabled state 

### ISSUE THREAD

**Issue by christophe-g** [PolymerElements/paper-dialog#122]
### Description

a button inside a paper-dialog changing its disabled state is not focusable through `tab`
### Expected outcome

once the button goes to a `disabled = false` state, pressing the `tab key` should allow focus 
### Actual outcome

the button gets activated, but cannot be focused via `tab`
### Live Demo

https://jsbin.com/yusuwi/edit?html,output
### Browsers Affected

- [x ] Chrome
  rest not tested

**Comment by valdrinkoshi** [comment]
Hi @christophe-g, thanks for reporting this! It is an issue with `iron-overlay-behavior` caching of the focusable nodes, and has already been reported here https://github.com/PolymerElements/iron-overlay-behavior/issues/184
Will close as it's a duplicate
