### ISSUE TITLE
Polymer (PSK 2.0) - paper-dialog doesn't work in Chromium based browsers.

### ISSUE THREAD

**Issue by alexhx5** [PolymerElements/paper-dialog#128]
### Description

Polymer `<paper-dialog>` doesn't work in Chromium based browsers.
### Expected outcome

To work
### Actual outcome

**Chrome console:**
Uncaught ReferenceError: dialog is not defined
### Live Demo

GIF: 
first Firefox / then Chrome with opened console

![1](https://cloud.githubusercontent.com/assets/13764106/18729935/808a13f4-805c-11e6-8a9c-520cb2d62dbd.gif)
### Steps to reproduce

Create new project with Polymer PSK 2.0

```
mkdir my-app
cd my-app
polymer init
```

Choose 4

![2](https://cloud.githubusercontent.com/assets/13764106/18730419/ebbfef98-805e-11e6-85d3-b8a5ed376052.PNG)

Install elements

```
bower install --save PolymerElements/paper-dialog
bower install --save PolymerElements/paper-button
```

Import it in **my-app.html**:

```
<link rel="import" href="../bower_components/paper-button/paper-button.html">
<link rel="import" href="../bower_components/paper-dialog/paper-dialog.html">
```

Create button and dialog

```
<paper-button raised onclick="dialog.open()">plain dialog</paper-button>
<paper-dialog id="dialog">
    <div>
          <h1>hello</h1>
     </div>
     <div class="buttons">
          <paper-button dialog-confirm>
               <iron-icon icon="close"></iron-icon>Close
           </paper-button>
     </div>
</paper-dialog>
```

Open the site on localhost:8080:
`polymer serve`
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10
### People

@robdodson

**Comment by valdrinkoshi** [comment]
Hi @AlexAlabyev, I assume you're adding the `paper-button` & `paper-dialog` in another custom element's template. If so, you cannot refer to it just by id (that works only for elements that are in the document root).
You have to do something like this:

```
  // in the template
  <paper-button raised on-click="openDialog">plain dialog</paper-button>
  <paper-dialog id="dialog">

...

  // in the Polymer element prototype
  openDialog: function() {
    this.$.dialog.open();
  }
```

**Comment by alexhx5** [comment]
Hi @valdrinkoshi could you please show me some more code? I'm a newbie and I don't understand how to implement that.

If I add the

```
openDialog: function() {
    this.$.dialog.open();
  }
```

into the 

```
  <script>
    Polymer({
      is: 'my-view1',
      openDialog: function() {
          this.$.dialog.open();
        }
    });
  </script>
```

It always opens up the 1st dialog only, if I use more than one 

```
  <paper-button raised on-click="openDialog">plain dialog</paper-button>
  <paper-dialog id="dialog">
```

on the page

It's weird that my initial code works in the Firefox and not in Chrome, though. (As it shown on the GIF - `dialog.open()` works in Firefox but not the Chrome)

**Comment by valdrinkoshi** [comment]
That's because Chrome already ships ShadowDom while Firefox uses the polyfill.

I didn't get what do you mean with using more than one button + dialog...If you have multiple dialogs you should give them different ids, to distinguish them. Or if you always put the button before the dialog you can do something like this:

``` html
<dom-module id="my-view1">
  <template>
     <paper-button on-click="_openNextDialog">Open next dialog</paper-button>
     <paper-dialog>next dialog</paper-dialog>
     <paper-button on-click="_openNextDialog">Open next dialog</paper-button>
     <paper-dialog>next dialog</paper-dialog>

     <paper-button trigger-for="dialog1" on-click="_openDialogByTrigger">Open dialog by trigger</paper-button>
     <paper-button trigger-for="dialog2" on-click="_openDialogByTrigger">Open dialog by trigger</paper-button>

     <paper-button on-click="_openDialog1">Open dialog 1</paper-button>
     <paper-button on-click="_openDialog2">Open dialog 2</paper-button>

     <paper-dialog id="dialog1">dialog 1</paper-dialog>
     <paper-dialog id="dialog2">dialog 2</paper-dialog>
  </template>
  <script>
    Polymer({
      is: 'my-view1',
      _openNextDialog: function(event) {
         // assume that the next sibling of the target is an overlay.
         var dialog = event.target.nextElementSibling;
         dialog.open();
      },
      _openDialogByTrigger: function(event) {
          var dialogId = event.target.getAttribute('trigger-for');
          // get dialog by id in the shadow root
          var dialog = this.$[dialogId];
          dialog.open();
      },
      _openDialog1: function(){
        this.$.dialog1.open();
      },
      _openDialog2: function(){
        this.$.dialog2.open();
      }
    });
  </script>
</dom-module>


```

**Comment by alexhx5** [comment]
@valdrinkoshi Oh wow, thank you sir, that worked! Nice to know there are people like you who care to help newbies like me to understand how it works. Thanks a lot!

**Comment by mrmcplad** [comment]
I found this very helpful!

Follow-up question: what is the distinction between `onclick` and `on-click`? When I was following this guide, I found that `onclick` doesn't work, but `on-click` does. Why?

**Comment by valdrinkoshi** [comment]
`onclick` is part of the [`GlobalEventHandlers`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onclick), while `on-click` is a polymer [event annotation](https://www.polymer-project.org/1.0/docs/devguide/events).
When you're building a polymer element, you use the polymer event annotation to bind that event to a method defined by your element e.g. `on-click="_openDialog1"`.
You could make it work using the `GlobalEventHandlers` by executing the method of a known instance element, e.g. 
```html
<my-view1 onclick="this._openDialog1()"`></my-view1>
```
But this is defined outside the dom-module, so it would leak this implementation detail.

**Comment by retrocausal** [comment]
This was really helpful.
If I may, I am trying to assign an id to the `paper-dialog` dynamically

The `DOM` itself, is _static shadow-dom_
```html
<a class="article-info-anchor" name="{{pmid}}" on-click="modalize"></a>
<!--pmid = projectfelix -->

<paper-dialog id="[[pmid]]">
        <h2>title</h2>
</paper-dialog>
```
However, in the event handler,
```js
let t = e.target.getAttribute('name');
console.log(t, this.$[t]);
this.$[t].open();
```
logs ` projectfelix` , ` undefined`

However, 

If I use the polymer 1.0 option 

```js
let t = "#" + e.target.getAttribute('name');
        console.log(t, Polymer.dom(this.root).querySelector(t));
```
it selects the element

**Comment by valdrinkoshi** [comment]
`this.$` is populated right before `ready()` - in other words the first time the element is attached to the DOM. Since you are creating dynamic elements, I'm assuming that happens after the 1st attach, hence you need to query the shadowRoot. You can use `$$` method to query the shadowRoot, e.g. `this.$$(t)`, or native DOM apis, e.g. `this.shadowRoot.querySelector(t)`
