### ISSUE TITLE
MacBook + Chrome bug for scrollable content

### ISSUE THREAD

**Issue by cbelden** [PolymerElements/paper-dialog#134]
### Description
Having a scrollable content area with children that have the "position: relative" style causes the scrollbar to appear offset vertically.

### Expected outcome
Scrollable content should be able to contain children that have the "position: relative" style without breaking the position of the scrollbar.

### Actual outcome
Scrollbar has a vertical offset (i.e. it's not aligned with the scrollable content).

### Live Demo
https://jsbin.com/giyicabihu/edit?html,css,js,output

### Steps to reproduce
1. Put a `paper-dialog` element in the page.
2. Add a child div that is scrollable (ie 'overlfow: auto' and fixed height)
3. Add enough child divs (with text) so that the scrollbar appears. Ensure these have the
'position: relative' style

### Browsers Affected

- [x] Chrome (could only reproduce on a MacBook, issue not reproducible on Chrome+Ubuntu)
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by cbelden** [comment]
Could the hooli tag get added?

**Comment by valdrinkoshi** [comment]
Hi @cbelden, this looks similar to https://github.com/PolymerElements/paper-dialog-behavior/issues/100 and https://github.com/PolymerElements/paper-dialog-scrollable/issues/32, and the root cause is on Chrome (see https://bugs.chromium.org/p/chromium/issues/detail?id=581136). Could you share the version of Chrome you have? Also, are you seeing the issue only with a screen with high density (e.g. macbook retina display)?

**Comment by cbelden** [comment]
Chrome:  54.0.2840.71
Device: macbook pro w/ retina display

Thanks for getting back so quickly!

**Comment by valdrinkoshi** [comment]
I can't repro, I'm on macbookpro w/ retina, Chrome 54.0.2840.98
![screen shot 2016-11-11 at 10 46 39 am](https://cloud.githubusercontent.com/assets/6173664/20226245/460d4c9c-a7fc-11e6-8792-f7335de3c4b9.png)

**Comment by florent1933** [comment]
I have the same problem. 

Chrome : Version 54.0.2840.98 (64-bit)
MacBook Pro (Retina 13 pouces, début 2015) : OSx El Capitan 10.11.6 (15G31)

<img width="1280" alt="capture d ecran 2016-11-21 a 00 30 35" src="https://cloud.githubusercontent.com/assets/3958123/20467173/c915e504-af81-11e6-9407-0ed6d8504455.png">

**Comment by MacTheZazou** [comment]
Corrected with chrome 55. Can close.

**Comment by cbelden** [comment]
Confirmed, can no longer reproduce. On MacBook Pro 15" Chrome version 55.0.2883.95 

Thanks :)
