### ISSUE TITLE
Modal shown by default if placed inside `dom-if` template

### ISSUE THREAD

**Issue by teckays** [PolymerElements/paper-dialog#14]
The modal dialog renders if placed inside `<template is="dom-if" if=""></template>` should it be this way?

**Comment by marcus7777** [comment]
If so it not working same as `dialog.open` modal if load with mod-if no model back ground

**Comment by morethanreal** [comment]
This seems to be caused by https://github.com/Polymer/polymer/issues/2037

**Comment by valdrinkoshi** [comment]
Got fixed by https://github.com/Polymer/polymer/commit/26112859d2ae6916f2066acafbf6c30f0fede797 (same fix of https://github.com/Polymer/polymer/issues/2037)
Closing this
