### ISSUE TITLE
Wrong focused element when paper dialog has custom element with paper-dropdown-menu's

### ISSUE THREAD

**Issue by KevinAsher** [PolymerElements/paper-dialog#146]
### Description
Having a custom element with paper-dropdown-menu's within a paper-dialog, after selecting a value for both dropdowns, the first selected dropdown gets focus. This only happens when Polymer is configured to use native shadow dom, when the custom element is not inside a paper-dialog this issue does not exist.

### Expected outcome

After selecting a value for the second dropdown, the element is expected to be focused.

### Actual outcome

The first selected dropdown gets focused.

### Live Demo
https://jsbin.com/xorihuqiqu/edit?html,output

### Steps to reproduce

1. Select a value for dropdown 1 and dropdown 2.
2. Notice how dropdown 1 is focused after selecting a value for dropdown 2.

### Browsers Affected

- [X] Chrome

**Comment by valdrinkoshi** [comment]
Cannot repro - see https://www.webcomponents.org/element/PolymerElements/iron-overlay-behavior/demo/demo/index.html
![restore-focus](https://cloud.githubusercontent.com/assets/6173664/26602534/a7ecfcda-4538-11e7-813c-2edc73a3756d.gif)
