### ISSUE TITLE
Issue with firefox

### ISSUE THREAD

**Issue by lanmower** [PolymerElements/paper-dialog#15]
The  'body' tags in the comment at the top of iron-overlay-behavior.html caused a problem with firefox.

I had to modify the comment locally as a temorary workaround to get it working.

Does this have to do with the polyfills replacing all 'body' tags? can it be made to ignore comments?

**Comment by vhdirk** [comment]
That problem is caused by browserSync, not Polymer.
See PolymerElements/polymer-starter-kit#126 for a workaround.
