### ISSUE TITLE
Re-centering dialog when its size changes

### ISSUE THREAD

**Issue by govis** [PolymerElements/paper-dialog#150]
### Description
Similar issue #68 was addressed by having the <code>iron-overlay-behavior</code> observe node changes to trigger resize. What if it's just the size that's changing without an underlining <code>dom-change</code> - for example a dialog with an auto-growing text editor does not currently get re-positioned when its size changes.

I tried adding a wrapper element with <code>IronResizableBehavior</code>, but that didn't seem to help - is there a recommended approach to tackle this scenario?

### Expected outcome
Dialog to stay centered

### Actual outcome
Dialog expands to the left and bottom

### Live Demo
http://jsbin.com/mibakuzuwo/edit?html,output

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
Your content needs to notify of the resize by firing an `iron-resize` event. `notifyResize` does exactly that (it is a method provided by `IronResizableBehavior`). So you can call `dialog.notifyResize()` after the content gets updated

**Comment by govis** [comment]
Thanks, I guess it can be done manually, a bit of a bummer and could be tricky in situations when user input is involved.

**Comment by danielvanmil** [comment]
So as I don't know whether my element will be used in a dialog (or other "sizable" element), should my custom element always throw a "iron-resize" event when I dynamically add content or change size etc.? So is this also implemented for the Polymer (paper) components? Is this documented somewhere?

And as we can have more nested elements, should all elements fire a "iron-resize" event as this not pass the shadow DOM boundaries of can we just "bubble up" the event?

**Comment by valdrinkoshi** [comment]
[ResizeObserver](https://developers.google.com/web/updates/2016/10/resizeobserver) would be the answer for that, but as it's not supported in all browsers, we use IronResizableBehavior which requires participation from resizing elements...
