### ISSUE TITLE
documentation for attributes

### ISSUE THREAD

**Issue by gurpreetatwal** [PolymerElements/paper-dialog#153]
It is incredibly hard to find the documentation for the `modal,` `with-backdrop`, `noCancelOnOutsideClick`, `noCancelOnEscKey` attributes. The `modal` attribute is given a short mention in the [accessibility section of)paper-dialog-behavior](https://github.com/PolymerElements/paper-dialog-behavior#accessibility) and the other attributes don't seem to be documented at all; they are also not specified as [properties of paper-dialog-behavior](https://github.com/PolymerElements/paper-dialog-behavior/blob/master/paper-dialog-behavior.html#L60).

There should be a table describing all the values that paper-dialog accepts in the readme. Similar to how [MDN lists out all attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output).

**Comment by valdrinkoshi** [comment]
https://www.webcomponents.org/element/PolymerElements/paper-dialog/elements/paper-dialog

**Comment by gurpreetatwal** [comment]
ah, okay. That was stupid on my part. 

Maybe add a link to the that page in the readme as some of the other polymer components have?

**Comment by valdrinkoshi** [comment]
It's already in the README.md 👌
![screen shot 2017-07-20 at 5 09 43 pm](https://user-images.githubusercontent.com/6173664/28443948-53d2926e-6d6e-11e7-8dae-d3b725d8fe8c.png)

**Comment by gurpreetatwal** [comment]
I apologize for the double stupidity on my part lol :joy: I never actually clicked that badge, I just assumed it was there to signify that component was published.  Up until now I had been clicking the "Demo and API Docs" links which some of the readmes have. Ex: [paper-toolbar](https://github.com/PolymerElements/paper-toolbar/blob/master/README.md). 

I'm going to close this issue, thanks for all your help!

**Comment by bsutton** [comment]
Actually can we re-open this issue.

I've just check the above noted links and none of them provide adequate documenation such as modal or backdrop.

The tags noted by @valdrinkoshi  are also a bad idea as like the original posted I had no idea that these were clickable links. They just look like a set of status flags.

So where is the doco on making a paper-dialog modal?

**Comment by valdrinkoshi** [comment]
@bsutton in w-c.org there is the full documentation of the properties & methods for the `<paper-dialog>` element, here the one for `modal` property  https://www.webcomponents.org/element/@polymer/paper-dialog/elements/paper-dialog#property-modal

**Comment by bsutton** [comment]
@valdrinkoshi thanks for the response.

Yes the link you provided is more helpful.

The question remains as to why the vaadin website and this git hub repo don't point to the more complete version.
The second question is why are there two alternate copies of the same document on the same web site.

As a dev that has heaps of vaadin experience and is used to the associated quality documentation associated with vaadin, the doco around vaadin's polymer components has been extremely disappointing and frustrating.

There are pieces all over the place and links that take you to bits which are completely useless.
