### ISSUE TITLE
neon-animation doesn't work in Polymer 2.0 

### ISSUE THREAD

**Issue by johnlim** [PolymerElements/paper-dialog#154]
### Description
In paper-dialog V2.0.0, setting entry-animation results in the following console errors 
```neon-animation-runner-behavior.html:40 Couldnt play ( slide-from-bottom-animation ). ReferenceError: KeyframeEffect is not defined
    at HTMLElement.configure (slide-from-bottom-animation.html:42)
    at HTMLElement._configureAnimations (neon-animation-runner-behavior.html:33)
    at HTMLElement.playAnimation (neon-animation-runner-behavior.html:93)
    at HTMLElement._renderOpened (paper-dialog.html:98)
    at HTMLElement.__openedChanged (iron-overlay-behavior.html:541)
    at nextAnimationFrame (iron-overlay-behavior.html:566)
```

### Expected outcome
Should show animation without error

### Actual outcome
No animation is shown and there are console errors

### Live Demo
https://jsbin.com/guditofini/edit?html,console,output
pls open chrome dev console to see the error displayed.
### Browsers Affected

- [x ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by web-padawan** [comment]
Have you included `web-animations-lite.min.js`? AFAIK you should do it for 2.0

**Comment by johnlim** [comment]
@web-padawan Thanks! Adding 
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/web-animations/2.2.1/web-animations-next.min.js"></script>
```
made it work. However, where is the information to add `web-animations-lite.min.js` located?  It wasn't immediately clear to me that this was a requirement. Thanks :)

**Comment by web-padawan** [comment]
@johnlim you need to import [this file](https://github.com/PolymerElements/neon-animation/blob/master/web-animations.html)

**Comment by valdrinkoshi** [comment]
Info available in the [README.md](https://github.com/PolymerElements/paper-dialog#changes-in-20)
> neon-animation 2.0 doesn't import the Web Animations polyfill, so you'll have to import it
> `<link rel="import" href="../neon-animation/web-animations.html">`

**Comment by johnlim** [comment]
@web-padawan @valdrinkoshi Thanks!

**Comment by WillieCubed** [comment]
Isn't `neon-animation` [deprecated](https://github.com/PolymerElements/neon-animation/issues/238), though? What are the plans for this?

**Comment by valdrinkoshi** [comment]
The plan is to replace these animations with more standard platform's animation APIs 👌 
See this blog post for more details https://www.polymer-project.org/blog/2017-07-12-an-update-on-neon-animation.html
