### ISSUE TITLE
Restoring focus for nested dialogs doesn't work well

### ISSUE THREAD

**Issue by galanovnick** [PolymerElements/paper-dialog#155]
### Description
Restoring focus to an element of the outer dialog (when the inner dialog is closed) doesn't work well if the outer dialog is inside another element shadow dom.

### Expected outcome
Inner dialog invocation button is focused after the inner dialog is closed.

### Actual outcome
The first outer dialog button is focused.

### Live Demo
http://jsbin.com/sarutorehu/edit?html,output

### Steps to reproduce

1. Click `Dialog from shadow root` button.
2. Navigate to `Inner` button using `Tab`.
3. Click `Inner` button.
4. Press `Escape`.

### Browsers Affected

- Chrome

**Comment by valdrinkoshi** [comment]
Hi @galanovnick, you need to set `restore-focus-on-close` to true in order to have a correct restoring of the focus http://jsbin.com/repuwez/3/edit?html,output

**Comment by galanovnick** [comment]
Hello, @valdrinkoshi. Doesn't look like `restore-focus-on-close` change anything. Actually, it seems like it works just the same with or without this property.
(recorded this gif from your jsbin)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9299809/31114961-206fdff8-a829-11e7-89aa-4d33d77b15f8.gif)

**Comment by valdrinkoshi** [comment]
You should test it outside the jsbin editor, as the result is contained in an iframe and looks like jsbin is modifying the `focus()` behavior or moving back the focus to the editor. Testing it from http://output.jsbin.com/repuwez/3/ works fine for me:
![restore-focus-on-close](https://user-images.githubusercontent.com/6173664/31137928-89700418-a821-11e7-85ee-76d9b1f50c97.gif)

**Comment by galanovnick** [comment]
Ok, it works for me as well. I have this issue in my application and now I know at least one possible source of the problem. Thanks.
