### ISSUE TITLE
2x attribute with-backdrop

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/paper-dialog#16]
view-source:https://elements.polymer-project.org/bower_components/paper-dialog/demo/index.html
line 131 
`<paper-dialog id="animated" with-backdrop entry-animation="scale-up-animation" exit-animation="fade-out-animation" with-backdrop>`

**Comment by morethanreal** [comment]
Appears to be fixed: https://github.com/PolymerElements/paper-dialog/blob/master/demo/index.html#L131
