### ISSUE TITLE
Ridiculous sizing of dialog

### ISSUE THREAD

**Issue by Mygod** [PolymerElements/paper-dialog#19]
The demo for `paper-dialog-behavior` works fine: https://elements.polymer-project.org/elements/paper-dialog-behavior?view=demo:demo/index.html&active=Polymer.PaperDialogBehavior

However when you reduce the height of the browser in the demo for `paper-dialog`: https://elements.polymer-project.org/elements/paper-dialog?view=demo:demo/index.html

The size of the dialog becomes ridiculous.

**Comment by Mygod** [comment]
Tested in Chrome 45.0.2438.3 dev (64-bit), Kubuntu 15.04

**Comment by morethanreal** [comment]
Can you describe the issue with more detail and/or a screenshot, for example which demo and what is the expected vs. actual result?

**Comment by Mygod** [comment]
http://imgur.com/RF11CFq
Here's a screenshot produced with Chrome Dev for Android. You can see the dialog is obviously too short...

**Comment by Mygod** [comment]
Ummm so is this going to be fixed?

**Comment by M0nter0** [comment]
I think 'Ridiculous' is something quite ambiguous. I've resolve your same situation just defining `min-width` and `min-height` at my stylesheet. You can also use the mixin `--paper-dialog`

**Comment by Mygod** [comment]
Sorry for my vocab. Isn't the mixin `--paper-dialog` already applied if I use `paper-dialog`?

I just did a further research and it seems this problem occurs only if the button that spawns the dialog is at the middle of the page which is totally unexpected...

I guess it's a `paper-dialog-behavior` issue then...

EDIT: I found out [the problem](https://github.com/PolymerElements/paper-dialog-behavior/issues/22#issuecomment-127603677). Can anyone fix this please?

**Comment by notwaldorf** [comment]
@Mygod `--paper-dialog` is applied as a mixin, but it's empty. It's where you would define your styles. See [this](https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins) for more details.

**Comment by valdrinkoshi** [comment]
I confirm, this can be achieved by setting the `min-height` through the mixin, and/or putting your content inside a scrollable container if the space is not enough.

``` html
<style is="custom-style">
  body {
    --paper-dialog: {
      min-height: 300px;
    };
  }
</style>

<!-- .... -->


<paper-dialog>
  <paper-dialog-scrollable>
    <div>Super long content</div>
  </paper-dialog-scrollable>
</paper-dialog>
```
