### ISSUE TITLE
[paper-dialog::_flattenBehaviorsList]: behavior is null, check for missing or 404 import

### ISSUE THREAD

**Issue by govis** [PolymerElements/paper-dialog#20]
Hi, I am getting the error on a page in a chrome extension that was vulcanized with the following command:

<code>vulcanize page.original.html --inline-script | crisper --html page.html --js page.js</code>

paper-dialogs become embedded in page's content and are visible upon load (paper-dialog version 1.0.1 is used). 

There's also <code>Resource interpreted as Document but transferred with MIME type text/css: "chrome-extension://lpobmfdlpaelckggjapikcolidlhmccn/import/paper-dialog-behavior/paper-dialog-common.css".</code> entry spit out in the console, which may or may not be related.

Do you have any idea what might be causing this? Thanks.

**Comment by govis** [comment]
Looks like it might be fine with latest vulcanize/crisper bits

**Comment by 34code** [comment]
Same issue with Rails asset compilation and minification
