### ISSUE TITLE
Repositioning paper-dialog when content changes

### ISSUE THREAD

**Issue by govis** [PolymerElements/paper-dialog#21]
Hi, have a paper-dialog that user can interact with. Different content gets presented upon interaction. It seems that IronOverlayBehavior is not currently handling changes in paper-dialog's size and it becomes off-centered when contents change.

I was wondering if you have any plans to change that and what would be the right way to trigger re-positioning in the meantime? Thanks.

**Comment by kungufli** [comment]
+1 this would be very useful

**Comment by anthonytordillos** [comment]
I think IronFitBehavior should cover this case, specifically refit().

https://elements.polymer-project.org/elements/iron-fit-behavior?active=Polymer.IronFitBehavior

**Comment by kungufli** [comment]
Thank you @anthonytordillos, this cover exactly this need, I just missed it. @govis just add a listener for dom-change event in your element and call this.$.yourdialogid.refit().

**Comment by govis** [comment]
That helps, thank you guys.
