### ISSUE TITLE
Hidden modal paper-dialog when used in paper-scroll-header-panel

### ISSUE THREAD

**Issue by dominik0711** [PolymerElements/paper-dialog#22]
Using a modal `paper-dialog` inside custom element with `paper-scroll-header-panel` the `paper-dialog` is hidden, see screenshot (Browser: **Chrome 44.0.2403.89 (64-bit)**:

![screen shot 2015-07-24 at 12 04 09](https://cloud.githubusercontent.com/assets/1011188/8872317/27c9569e-31fc-11e5-8fd3-cc1daf40d860.png)

`paper-dialog` is visible when I use **Safari Browser 8.0.7 (10600.7.12)**, see:

![screen shot 2015-07-24 at 11 52 01](https://cloud.githubusercontent.com/assets/1011188/8872340/5ddf5116-31fc-11e5-8799-ec4ae5051318.png)

Any suggestions why Chrome is **not** displaying the `paper-dialog` correctly?

**Comment by glaucomunsberg** [comment]
+1

**Comment by glaucomunsberg** [comment]
@dominik0711 I solved this problem putting the paper-dialog inside the paper-header-panel and adding position: fixed css in the paper-dialog 

```
<body unresolved>
    <paper-drawer-panel>
        <paper-header-panel mode="seamed">
             ...
             <paper-dialog modal style='position: fixed;'>
                ...
             </paper-dialog>
             ....
         </paper-header-panel>
   </paper-drawer-panel>
</body>
```

**Comment by valdrinkoshi** [comment]
This issue has been fixed, see example here 
http://jsbin.com/daseje/1/edit?html,output
