### ISSUE TITLE
Calling "resetFit()" on a modal dialog pushes it behind the overlay

### ISSUE THREAD

**Issue by tigerhawkvok** [PolymerElements/paper-dialog#24]
Says it all.

![screenshot 2015-07-30 01 13 13](https://cloud.githubusercontent.com/assets/165937/8978578/2cf979d6-3658-11e5-8e17-6090f19d74a7.png)

**Comment by rubenstolk** [comment]
@tigerhawkvok I think you want to use `refit()` rather than `resetFit()`

**Comment by valdrinkoshi** [comment]
confirming, as per documentation

> resetFit() resets the target element's position and size constraints, and clear the memoized data.

you need to call `fit()` after `resetFit()`, or just `refit()` (which does `resetFit` then `fit`)
