### ISSUE TITLE
"Constrain" behaves incorrectly on mobile

### ISSUE THREAD

**Issue by tigerhawkvok** [PolymerElements/paper-dialog#25]
Calling `.fit()` or `.constrain()` fails to adequately do so.

Note this post-constrain fitting:

![screenshot 2015-07-30 01 27 58](https://cloud.githubusercontent.com/assets/165937/8980038/c95dc4da-3662-11e5-90ff-f0d5af484624.png)

Which merely pushes the bottom off! If it's `.fit()` or `.center()`d, too, you can't see the top OR bottom.

The dialog isn't forcing the `<paper-dialog-scrollable>` to the right size, from what I can tell. The scrollable is something grossly tall, and the dialog is wrapped around it.

Here's the full implementation for a reference: http://ssarherps.org/cndb/polymer1beta/#bGFtcHJvcGVsdGlzK3pvbmF0YSZsb29zZT10cnVl

Live site is running Polymer 0.5, which behaves correctly.

**Comment by valdrinkoshi** [comment]
Hi @tigerhawkvok, I cannot reproduce the issue on your website and neither in an isolated example like this http://jsbin.com/rocaxa/1/edit?html,output

Is the issue persisting? Could you please provide an example?

**Comment by valdrinkoshi** [comment]
Feel free to reopen in the issue persists.
