### ISSUE TITLE
Modal dialog not closing

### ISSUE THREAD

**Issue by pensierinmusica** [PolymerElements/paper-dialog#27]
Hi,

If the `<paper-dialog>` element has the attribute `modal="true"`, the dialog does not close when the user clicks outside of the dialog area (as it properly does instead without `modal="true"`).

The only interaction event that seems to close the dialog is the `esc` key (that, btw, is not available on mobile).

Any idea when this could be fixed? Thanks!

**Comment by hawkett** [comment]
This behaviour [is documented](https://elements.polymer-project.org/elements/paper-dialog-behavior?active=Polymer.PaperDialogBehavior):

`If modal is true, this implies no-cancel-on-outside-click and with-backdrop.`

So to get the behaviour you're after, you should just set `with-backdrop` on your dialog (not `modal`). It's a property on `IronOverlayBehavior`, but the documentation is a little broken - I can't get the `IronOverlayBehavior` docs show up - it keeps redirecting to `iron-overlay-backdrop` atm.

**Comment by pensierinmusica** [comment]
@hawkett I see, thanks for the tip!

**Comment by pensierinmusica** [comment]
In this case though, when `modal=true`, the `esc` button should not close the dialog.

**Comment by hawkett** [comment]
There's an option [documented](https://elements.polymer-project.org/elements/iron-overlay-behavior?active=Polymer.IronOverlayBehavior) for handling the `esc` key:

```
noCancelOnEscKey
Boolean
default: false
Set to true to disable canceling the overlay with the ESC key.
```

The double negative makes it a little hard to reason about :)

**Comment by pensierinmusica** [comment]
@hawkett, awesome, thanks for the tip! Imho this should be the default behavior when `modal="true"`.
From a UX perspective, the `esc` key and clicking outside is about the same. Either they're both allowed, or they're both disabled. Keeping one active and the other one disabled doesn't make much sense to me as a standard setting. Is the Polymer team up for a small change?

**Comment by hawkett** [comment]
Quick disclosure - I'm not on the Polymer team (or at Google).

**Comment by pensierinmusica** [comment]
@ebidel, @addyosmani is anyone actively looking at these issues by any chance? #27, #28, #29

I Imagine the Polymer team has tons of more relevant things to take care of at the moment, but just wanted to check these repos are still actively maintained.

Thanks!

**Comment by pensierinmusica** [comment]
Hi @notwaldorf, this issue and the ones mentioned in the previous comment (#28 and #29) have been open for about 2 months now without getting any feedback. I really understand that the Polymer team is super-busy with more important things to do, but do we have any chance to make some progress here? Thanks!!

**Comment by valdrinkoshi** [comment]
this looks like a question/enhancement, and should be moved to iron-overlay-behavior repo (since `noCancelOnEscKey` is defined there). 
As of now, this can be already achieved by setting `paper-dialog` (or any element that inherits `IronOverlayBehavior` for that matter) like this:

``` html
<paper-dialog modal no-cancel-on-esc-key>
<div>my content</div>
</paper-dialog>
```

**Comment by valdrinkoshi** [comment]
@cdata @notwaldorf FYI

**Comment by valdrinkoshi** [comment]
~~This issue was moved to PolymerElements/iron-overlay-behavior#66~~
Will take care of this in `paper-dialog-behavior`

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/paper-dialog-behavior#64
