### ISSUE TITLE
Host CSS font styles not respected

### ISSUE THREAD

**Issue by pensierinmusica** [PolymerElements/paper-dialog#28]
Imho the dialog should adopt the same CSS font styling rules that are defined in the host.

Why on earth for example are paper elements trying to enforce the "Roboto" `font-family` everywhere? 

Every app / website has different design choices, that should be coherently applied among its elements.

**Comment by bendavis78** [comment]
It doesn't look to me like paper-dialog is enforcing font-family anywhere...

**Comment by pensierinmusica** [comment]
@bendavis78 maybe I used the wrong term here, by "enforcing" I meant that it's not inheriting the `font-family` and other CSS styles from the context, which doesn't make too much sense for me.

If I put a dialog box in a website, I want it to have the same typographical settings as its host environment by default.

**Comment by pensierinmusica** [comment]
@notwaldorf any update on this by any chance? Cheers!

**Comment by valdrinkoshi** [comment]
paper elements follow the Material Design specs, hence they set "Roboto" as their font.
This is achieved by applying common mixins across these paper-elements. Typography mixins are defined here 
https://github.com/PolymerElements/paper-styles/blob/master/typography.html

`paper-dialog` [applies different mixins](https://github.com/PolymerElements/paper-dialog-behavior/blob/master/paper-dialog-shared-styles.html#L22), you can override any of those.

E.g. Here's how to change the font-family for body and title of all paper-elements:

``` html
<style is="custom-style">
  * {
    --paper-font-body1: {
      font-family: monospace;
    };
    --paper-font-title: {
      font-family: monospace;
    };
  }
</style>
```

**Comment by pensierinmusica** [comment]
@valdrinkoshi agreed, I just don't like this approach at all. I find it very annoying. Why wouldn't paper elements just respect the host environment design choices **by default**, and only fill-in with default styles when there are no specified rules in the host environment?

Imho this would be the best of both worlds, and would allow for a much smoother and widespread adaptability. Otherwise each time the user has to specify all these values to overwrite aggressive defaults, just to have the style fit with the environment design choices. It's bad UX, and feels like Google wants to impose their design style everywhere.

**Comment by cdata** [comment]
@pensierinmusica As @valdrinkoshi pointed out, we adhere to the Material Design spec for our `paper-*` components. Also, we enable hooks into our style system via CSS Custom Properties. So, any parent scope can override the mixin that applies the font-family. For example, in your `root` scope, or in some wrapping `host`, you could do something like this:

``` css
paper-dialog {
  /* Change all of the fonts within the style scope of the `paper-dialog` element
   * to use a custom font family: */
  --paper-font-common-base: {
    font-family: Helvetica Neue;
  }
}
```

Our philosophy here is to apply a default style that makes sense for the Material Design spec, and then enable users to maximally customize and theme the components via a styling API exposed as CSS Custom Properties.

This approach is very "bleeding edge" and unfamiliar, so it is totally understandable that you do not like it at a glance. If you are interested in getting some Material Design components without the style semantics that Polymer elements rely on, there are other great options out there such as [Material Design Lite](http://www.getmdl.io/).

Exposing styling APIs through ShadowDOM boundaries as CSS Custom Properties has some major advantages over the traditional approach to styling components with CSS. Polymer Elements embrace and take full advantage of this approach.

If you are interested in learning more, I definitely recommend reading up on ShadowDOM and CSS Custom Properties. They will be a big part of the future of the web platform. Philip Walton just wrote a nice article about [CSS Custom Properties](http://philipwalton.com/articles/why-im-excited-about-native-css-variables/) yesterday and HTML5 Rocks has a great explainer on [ShadowDOM](http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom/).

**Comment by pensierinmusica** [comment]
@cdata thanks for your feedback, I'm familiar with Web Components, Shadow DOM, and Polymer, having built a few projects with these technologies in the past few months. I understand the approach you mention with mixins. Still imho this is not DRY and is bad UX, since it forces the developer to repeat a CSS rule that has already been set.

**Comment by cdata** [comment]
Okay then. Definitely check out Material Design Lite. It sounds like you would be happier with those styling semantics. Cheers!

**Comment by CodeRedPaul** [comment]
@cdata Hey - I'm actually having the opposite problem where I can't get the Material Design Styles to apply but it defaults to the page's styles. Wondering if you could help, please? 

I've created a new issue for it here: https://github.com/PolymerElements/paper-dialog/issues/170

Thanks so much.

Paul
