### ISSUE TITLE
Error with dialog sizing in mobile devices

### ISSUE THREAD

**Issue by pensierinmusica** [PolymerElements/paper-dialog#29]
Hi,

I'm having some problems with `<paper-dialog>` sizing on mobile devices.

Let's take an iPhone 6 viewport for example.

As you can see, part of the dialog is cut when `open()` is invoked.

![img_2293](https://cloud.githubusercontent.com/assets/3594037/9140350/cff47238-3d30-11e5-8df8-2e4b9d65577e.PNG)

If you scroll up and down a bit with the phone though in some moments it fixes itself.

![img_2294](https://cloud.githubusercontent.com/assets/3594037/9140352/d3cd7d96-3d30-11e5-9c42-51bb6305e962.PNG)

The overall UX feels buggy, any idea how to fix it and when it will be done?

Thanks!

**Comment by ghost** [comment]
+1 I too am hitting this same problem.
I was tinkering with the styles and code thinking it was something i was messing up.
But when you try the component demo page it fails on mobile:

https://elements.polymer-project.org/elements/paper-dialog?view=demo:demo/index.html&active=paper-dialog

Would be good if this is fixed, Or guidance about how best to adjust is given.

**Comment by morganwu** [comment]
+1
Following is the inner html of my login dialog

``` html
                <div class="relative" style="height: 50px;">
                    <div class="layout horizontal relative" style="width: 100%; height: 100%;">
                        <div class="fit layout vertical center-center">
                            <span class="title">Please login</span>
                        </div>
                        <div class="fit layout horizontal center">
                            <div class="flex"></div>
                            <paper-icon-button icon="clear" dialog-dismiss></paper-icon-button>
                        </div>
                    </div>
                </div>

                <paper-input id="username" label="Email"></paper-input>
                <paper-input id="password" type="password" label="Password"></paper-input>
                <div style="margin: 10px;">
                    <paper-button raised class="flex button-green" on-click="onClickLoginBtn">Login</paper-button>
                </div>
                <div class="layout horizontal center-center" style="margin: 10px;">
                    <paper-button class="flex-5">Forgot password</paper-button>
                    <paper-button class="flex-5" on-tap="onTapSignup">Signup</paper-button>
                </div>
```

and here is the rendering result
![image](https://cloud.githubusercontent.com/assets/1981522/10724124/ebc4c0fc-7bfc-11e5-9827-10eb0cd13599.png)

**Comment by morganwu** [comment]
I think I found the reason, it seems paper-dialog is measured based on its parent's size, in my case I adjusted the parent node's height to match the size of the viewport, then everything works well. I am not sure if it is possible and why not dialog's size be calculated according to viewport size no matter where dialog is, but I won't dig deeper right now.

**Comment by valdrinkoshi** [comment]
I cannot reproduce it with `v1.0.3` http://jsfiddle.net/valdrinkoshi/vw6gLjy8/1/
Tested on iphone simulator and chrome on Nexus 5.

**Comment by pensierinmusica** [comment]
@valdrinkoshi I've tried in iOS simulator what @gedw99 mentioned and it does some weird "flashing":

https://elements.polymer-project.org/elements/paper-dialog?view=demo:demo/index.html&active=paper-dialog

**Comment by valdrinkoshi** [comment]
True, that's because we have `onclick` listener on each session, and safari applies an highlight effect on it https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariWebContent/AdjustingtheTextSize/AdjustingtheTextSize.html

re-opening
