### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by DmitryOlkhovoi** [PolymerElements/paper-dialog#35]
When i use Polymer's dom api in close event handler, i get it error. When i several times click on button that perform close of the dialog and open it again
Trace looks like this
Polymer.DomApi.DomApi.querySelectorAll @ polymer-mini.html:968Polymer.DomApi.DomApi.querySelector @ polymer-mini.html:700_focusNode @ iron-overlay-behavior.html:166Polymer.IronOverlayBehaviorImpl._applyFocus @ iron-overlay-behavior.html:387focusOverlay @ iron-overlay-manager.html:74Polymer.IronOverlayBehaviorImpl._applyFocus @ iron-overlay-behavior.html:388focusOverlay @ iron-overlay-manager.html:74Polymer.IronOverlayBehaviorImpl._applyFocus @ iron-overlay-behavior.html:388focusOverlay @ iron-overlay-manager.html:74Polymer.IronOverlayBehaviorImpl._applyFocus @ iron-overlay-behavior.html:388focusOverlay @ iron-overlay-manager.html:74Polymer.IronOverlayBehaviorImpl._applyFocus @ iron-overlay-behavior.html:388focusOverlay @ iron-overlay-manager.html:74Polymer.IronOverlayBehaviorImpl._applyFocus @ iron-overlay-behavior.html:388focusOverlay @

**Comment by valdrinkoshi** [comment]
hi @DmitryAuine, could you provide an example? 
I've tried with http://jsfiddle.net/valdrinkoshi/wx48axw0/ and i cannot reproduce it.

**Comment by valdrinkoshi** [comment]
Feel free to reopen the issue if the problem persists.
