### ISSUE TITLE
paper-dialog closes when you click on it

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-dialog#39]
`paper-dialog` now automatically closes when you click over it (on every part, it even closes if you click on a `paper-input` to write some text). This is probably caused by some recent change to the `iron-overlay-behavoir`, I suspect.

**Comment by samccone** [comment]
@kungufli What device are you testing this one?

**Comment by kungufli** [comment]
I'm testing in Chrome 45.0.2454.101 on a Linux machine. The problem appeared today after I bower updated the bower_components.

**Comment by samccone** [comment]
kk thanks for the debug info @kungufli !

**Comment by ebidel** [comment]
@azakus @cdata did https://github.com/PolymerElements/iron-overlay-behavior/commit/ad1cda00708d1a79539b7ef511454d576ed779f6 break this?

**Comment by kungufli** [comment]
Seems fixed for me after today bower update. Thanks.

**Comment by ebidel** [comment]
@cdata Shall we close?

**Comment by valdrinkoshi** [comment]
Tested again, the issue is fixed in `v1.0.3`. Closing this

**Comment by cineq** [comment]
Hi I am facing with same issue described here. I am using master version
