### ISSUE TITLE
Dialog not centered when CSS max-height and max-width applied

### ISSUE THREAD

**Issue by motss** [PolymerElements/paper-dialog#41]
Are we allowed to explicitly set `max-height` and `max-width` to `paper-dialog`? The dialog is not centered if `max-height` and `max-width` are set.
[Code sample](http://jsbin.com/vekawevora/edit?html,output)

Expected Result
![dialog-centered-small](https://cloud.githubusercontent.com/assets/10607759/10198515/f9612724-67ce-11e5-86dd-88d9bb5275e9.png)

When `max-height` and `max-width are set...
![dialog-not-centered-small](https://cloud.githubusercontent.com/assets/10607759/10198514/f9600254-67ce-11e5-8e73-a907ca50ba5e.png)

**Comment by freshp86** [comment]
I am facing the same issue. max-width causes the dialog to not be properly centered. Calling `fit()` or `center()` does not seem to center it either. If I change max-width to width, then it get centered properly.

**Comment by valdrinkoshi** [comment]
This behavior is implemented in `IronFitBehavior`, and on my tests I see `paper-dialog` gets correctly centered the first time is opened. But if we close it and open it again, the dialog positioning is wrong.
![paper-dialog](https://cloud.githubusercontent.com/assets/6173664/11644306/ac3189ce-9cff-11e5-9b91-92e61b6b2bc1.gif)

**Comment by valdrinkoshi** [comment]
Moved this issue to the correct repo https://github.com/PolymerElements/iron-fit-behavior/issues/29
Closing this one
