### ISSUE TITLE
ESC Closing all dialogs when nested

### ISSUE THREAD

**Issue by erichnascimento** [PolymerElements/paper-dialog#45]
When key ESC is pressed in nested dialogs, all dialogs are closed instead of the highest dialog only.

**Comment by valdrinkoshi** [comment]
good catch @erichnascimento, this should be fixed in `IronOverlayBehavior`, I'll move it there

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/iron-overlay-behavior#62
