### ISSUE TITLE
incorrect encoding

### ISSUE THREAD

**Issue by ghost** [PolymerElements/paper-dialog#46]
From Chrome console : 
Resource interpreted as Document but transferred with MIME type text/css: "https://dev.g.x/assets/bower_components/paper-dialog-behavior/paper-dialog-common.css".

Still having this issue today with latest bower update. These issues (already resolved) are related : 
https://github.com/PolymerElements/paper-slider/issues/68
https://github.com/PolymerElements/paper-radio-button/issues/52
https://github.com/PolymerElements/paper-item/issues/26

**Comment by valdrinkoshi** [comment]
Fixed by #70
