### ISSUE TITLE
Focusing on a paper-input element shrinks dialog (chrome for android).

### ISSUE THREAD

**Issue by kevinwestern** [PolymerElements/paper-dialog#48]

**Comment by valdrinkoshi** [comment]
Hi @kevinwestern, what do you mean with "shrinks"? This is what I see on chrome on nexus 5
http://jsbin.com/mihiyejaje/2/edit?html,output
![screenshot_20151208-101521](https://cloud.githubusercontent.com/assets/6173664/11664129/cd1b6606-9d94-11e5-92d0-8433a7612308.png)

**Comment by valdrinkoshi** [comment]
Closing this, feel free to re-open if it's still an issue (check https://github.com/PolymerElements/paper-dialog/blob/master/CONTRIBUTING.md)
