### ISSUE TITLE
Lack of Proper Documentation for <paper-dialog>

### ISSUE THREAD

**Issue by pippintook** [PolymerElements/paper-dialog#49]
On the polymer elements catalog, it would be very handy if there was some actual information about how to properly toggle the paper-dialog.

**Comment by TheMoonDawg** [comment]
If you look at the documentation, you'll see all of the methods you need to open/close the dialog.

https://elements.polymer-project.org/elements/paper-dialog

The open() and close() methods are responsible for showing/hiding the dialog window.

You can also use the toggle() method to toggle the dialog on or off.

**Comment by valdrinkoshi** [comment]
Closing this, feel free to re-open with more details if the issue persists
