### ISSUE TITLE
paper-dialog dont close in iphone

### ISSUE THREAD

**Issue by alonhar** [PolymerElements/paper-dialog#50]
I use phonegap with iphone, The dialog-box does not close by clicking outside the dialog.
it works ok on chrome firefox on android, but not in iphone.

**Comment by valdrinkoshi** [comment]
Fixed with `v1.0.3`, tested using ionic framework
![cordova](https://cloud.githubusercontent.com/assets/6173664/11664988/aa191cc0-9d99-11e5-8212-02a8edffd1fc.gif)
