### ISSUE TITLE
Bower - EINVALID - Failed to read /tmp/con/bower/neon-animation-14702-xwhFrF/bower.json

### ISSUE THREAD

**Issue by ConAntonakos** [PolymerElements/paper-dialog#51]
Hi. I keep getting these `EINVALID` errors when trying to install paper components. I've seen errors in other repos, and I've reinstalled bower in many different versions from ~1.4.x to ~1.5.x, and nothing is working.

Additional error details:
The "main" field has to contain only 1 file per filetype; found multiple .html files: ["neon-animated-pages.html","neon-animatable-behavior.html","neon-animation-behavior.html","neon-animation-runner-behavior.html","neon-shared-element-animatable-behavior.html","neon-shared-element-animation-behavior.html","neon-animatable.html","neon-animations.html"]

Any ideas? I'd be happy to elaborate.

**Comment by ConAntonakos** [comment]
Just wanted to quickly update that I was finally able to `bower install` this component on bower `1.13.12`. A lot of trial and error. Any ideas why this is happening? Do I need to update my node? Bower version 1.4+ seems to just not want to work with the current structure of paper elements.

**Comment by valdrinkoshi** [comment]
Hi @ConAntonakos, still facing this issue? I'm using bower 1.7.0 and I didn't see it happening so far.

**Comment by valdrinkoshi** [comment]
Feel free to reopen the issue if the problem persists.

**Comment by ConAntonakos** [comment]
Hi, @valdrinkoshi. Thanks for your response. So far, so good. I haven't tried the latest bower version, but I'm on 1.4.2 with no issues. :smile:

**Comment by valdrinkoshi** [comment]
\o/
