### ISSUE TITLE
Passing parameters to a dialog

### ISSUE THREAD

**Issue by deepak229** [PolymerElements/paper-dialog#52]
Hi,
I have a requirement where, I need to send a modal object to a dialog and display that information in there. Is there a way to do that? I searched for it, and did not find any documentaiton around.

**Comment by akc42** [comment]
You don't give very much information about what you are trying to do.

I would wrap the paper-dialog in a custom element, and then in the content of the paper dialog put elements that use data binding to access the data from your "modal object"
