### ISSUE TITLE
Touch events leak through to underlying page

### ISSUE THREAD

**Issue by marcushellberg** [PolymerElements/paper-dialog#59]
Tapping a button that closes the dialog also taps whatever element happens to be underneath in the main window. The same does not seem to happen with a normal mouse click.

**Comment by alexandrubichis** [comment]
+1

**Comment by halkar** [comment]
Same issue with scrolling.

**Comment by valdrinkoshi** [comment]
This is achievable by setting `modal=true` and the custom css property `--iron-overlay-backdrop-background-color`.
`paper-dialog` implements `IronOverlayBehavior`, hence uses the `iron-overlay-backdrop` which can be styled https://elements.polymer-project.org/elements/iron-overlay-behavior?active=iron-overlay-backdrop

``` html
<style is="custom-style">
  iron-overlay-backdrop {
    --iron-overlay-backdrop-background-color: transparent;
  }
</style>
<button onclick="document.querySelector('paper-dialog').toggle()">Open</button>
<paper-dialog modal>
  <h2>Test</h2>
  <button onclick="document.querySelector('paper-dialog').toggle()">Close</button>
</paper-dialog>
```

**Comment by valdrinkoshi** [comment]
The drawback is that, because it is a modal, you'll loose the autoClosing feature when clicking outside of the `paper-dialog`. You can have this feature by adding the script:

``` html
<style is="custom-style">
  iron-overlay-backdrop {
    --iron-overlay-backdrop-background-color: transparent;
  }
</style>
<button onclick="document.querySelector('paper-dialog').toggle()">Open</button>
<paper-dialog modal>
  <h2>Test</h2>
  <button onclick="document.querySelector('paper-dialog').toggle()">Close</button>
</paper-dialog>

<script>
  var dialog = document.querySelector('paper-dialog');
  dialog.backdropElement.addEventListener('click', dialog.close.bind(dialog));
</script>
```

@cdata WDYT? Should the leaking of events of `paper-dialog-behavior` be considered a bug or feature?

**Comment by valdrinkoshi** [comment]
In this example we see that the click doesn't leak to the document http://jsbin.com/leyafi/5/edit?html,output
All buttons will execute `toggle` function. When the dialog is opened and we click on the internal button, we see that the method `toggle()` is called only once (by the button where we just clicked)

Closing this...

**Comment by rubenstolk** [comment]
@valdrinkoshi I think the real issue is with `on-tap` rather than `on-click`. You can easily replicate this:
- Open your example (http://jsbin.com/leyafi/5/edit?html,output)
- Switch Chrome to for example iPhone 6 mode using the developer toolbar
- Replace `on-click` with `on-tap`
- When you now tap the button in the modal, the underlying button get's a strange focus...

**Comment by valdrinkoshi** [comment]
@rubenstolk, did some tests both on real devices and simulators with this jsbin http://jsbin.com/leyafi/9/edit?html,output, and this is what I could experience:
- on Safari in iOs Simulator tap doesn't leak
- on both Safari & Chrome in iPad device tap doesn't leak
- on Chrome Dev Tools with iPhone 6 simulator tap leaks
- on Chrome in Android Nexus 5x tap leaks

Looks like an issue with Polymer's `tap` gesture, I'll file a bug there.

**Comment by valdrinkoshi** [comment]
Filed here https://github.com/Polymer/polymer/issues/3704

**Comment by rubenstolk** [comment]
Thanks @valdrinkoshi!
