### ISSUE TITLE
Model dialog allows element outside dialog to be focused

### ISSUE THREAD

**Issue by nick211** [PolymerElements/paper-dialog#63]
When using the tab key to cycle through the elements in a model paper-dialog, when the last element is reached, the focus moves to the browser. When tab is pressed again, the focus moves to the first element on the page, which is outside the dialog, and which should not be focusable. (instead, the first element inside the dialog should get the focus).

Example:

```
<paper-button id="dialog-button">Open dialog</paper-button>

<paper-dialog id="dialog" modal>
  <h2>Test</h2>
  <paper-button></paper-button>

  <paper-input></paper-input>               

  <section class="buttons">
    <paper-button>Cancel</paper-button>
    <paper-button>OK</paper-button>
  </section>
</paper-dialog>

<script>
  document.querySelector('#dialog-button').addEventListener('click', function() {
    document.querySelector('#dialog').open();
  });
</script>
```

**Comment by valdrinkoshi** [comment]
Could not reproduce the issue with `v1.0.3`
Open the dev console & log `document.activeElement` every second (`setInterval(function(){console.log(document.activeElement)},1000)`) then press tab/shift+tab & check the logs. When the dialog is opened, the focus goes outside only at the `<body>`

**Comment by togiles** [comment]
I'm able to reproduce this issue still:

http://embed.plnkr.co/VPNA4xvZWFtL3O1vPRVe/

Will file new issue to track.
