### ISSUE TITLE
Focus is not restored after closing modal dialog

### ISSUE THREAD

**Issue by nick211** [PolymerElements/paper-dialog#64]
When closing a modal dialog, focus should be restored to the element that had the focus before opening the dialog. Example:

```
<paper-button id="dialog-button">Open dialog</paper-button>

<paper-dialog id="dialog" modal>
  <h2>Test</h2>
</paper-dialog>

<script>
  document.querySelector('#dialog-button').addEventListener('click', function() {
    document.querySelector('#dialog').open();
  });
</script>
```

Steps to reproduce:
1. Move focus to "open dialog" button using tab key.
2. Hit enter to open dialog.
3. Hit esc to close dialog.

Expected behavior: "open dialog" button should be focused, but it is not.

**Comment by anthonytordillos** [comment]
I filed this a while back in the paper-dialog-behavior component:

PolymerElements/paper-dialog-behavior/issues/32

**Comment by valdrinkoshi** [comment]
closing this as it's a duplicate.
