### ISSUE TITLE
Element with autofocus only gets autofocus the first time the dialog is opened

### ISSUE THREAD

**Issue by dfreedm** [PolymerElements/paper-dialog#65]
_From @viridium on September 5, 2015 3:13_

In a `paper-dialog`, I have a `paper-input` with `autofocus`. Open the dialog once -- the autofocus works fine. Open the dialog a second time -- the input no longer has focus.

_Copied from original issue: Polymer/polymer#2418_

**Comment by dfreedm** [comment]
_From @quaintcow on October 27, 2015 5:13_

Happens with me too. calling .focus() doesn't appear to help either.

**Comment by valdrinkoshi** [comment]
issue cannot be reproduced with `v1.0.3` http://output.jsbin.com/riqihu/
(source here http://jsbin.com/riqihu/edit?html,output)

**Comment by viridium** [comment]
Can we confirm that your example captures the issue in a previous 1.0.x version? It may be that your example never captured the issue to begin with.

**Comment by valdrinkoshi** [comment]
hi @viridium, `paper-dialog` isn't really doing much (in terms of implementation) for handling the focus.
This is done in `IronOverlayBehavior`, so this issue should go there if the problem still exists.
I've created a more complex example here http://jsbin.com/pufiyu/9/edit?html,output
Notice that I'm trying very old versions, and i cannot reproduce the problem

``` html
<base href="http://polygit.org/paper-dialog-behavior+v1.0.0/paper-dialog+v1.0.0/components/"> 
```

If you want to try the latest version, change that line to:

``` html
<base href="http://polygit.org/components/"> 
```

Concerning the issue you reported, I've reproduced it as you described and i cannot see the issue. Please provide one example and I'll be happy to look at it.

**Comment by viridium** [comment]
None of those inputs takes focus for me on Chrome 46.0.2490.86 on OS X Yosemite, in either the 1.0.0 or the latest version of Polymer.

**Comment by valdrinkoshi** [comment]
You need to try it without the editor active, because jsbin will handle the focus when on edit mode.
http://jsbin.com/pufiyu/9

**Comment by viridium** [comment]
Indeed, your example works for me now.

Here is an example that exposes the original problem: http://output.jsbin.com/poquvocaka

The first time, the input takes focus. Hit ESC to close the dialog, then reopen the dialog: now the input no longer has focus. This is with the latest Polymer version.

**Comment by viridium** [comment]
Here is an even more bare-bones example: http://jsbin.com/mozezucacu

**Comment by valdrinkoshi** [comment]
You need to set `autofocus` to a child of the dialog. `x-my-input` is responsible of forwarding the focus. Here a working example, notice the `tabindex = -1` and where `autofocus` got moved: 
code http://jsbin.com/yavoguj/9/edit?html
test http://jsbin.com/yavoguj/9/

**Comment by prudhvit** [comment]
If we use paper-dialog with paper-input in main html file then autofocus is working. But when we use the same paper-dialog with  in any other component the it is no working.
