### ISSUE TITLE
paper-dialog with entry-animation removes focus from autofocus element

### ISSUE THREAD

**Issue by dfreedm** [PolymerElements/paper-dialog#66]
_From @viridium on September 5, 2015 3:10_

In a `paper-dialog`, I have a `paper-input` with `autofocus`. When the dialog opens, the input is focused. So far so good.

Add an `entry-animation` to the dialog, and the input loses focus as soon as the animation is done.

_Copied from original issue: Polymer/polymer#2417_

**Comment by dfreedm** [comment]
_From @emankovski1 on October 21, 2015 17:28_

+1

**Comment by valdrinkoshi** [comment]
Tested and cannot reproduce with `v1.0.3` http://jsbin.com/watobu/ (source here http://jsbin.com/watobu/edit?html,output)

**Comment by viridium** [comment]
Can we confirm that your example captures the issue in a previous 1.0.x version? It may be that your example never captured the issue to begin with.
