### ISSUE TITLE
Paper-dialog not positioned correctly for dynamically populated content

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-dialog#68]
_From @richieb on January 13, 2015 20:53_

If you have a paper-dialog element set to display dynamic content, as illustrated in the code below, it does not display correctly on the screen, not centered. It is off to the side and below somewhere. Sure, it does display correctly if it is NOT dynamically populated.

Now, although it shows up not centered on launch, if you resize the browser window, then the dialog readjusts and positions itself to the correct **centered** position. I am much too busy right now to re-create a jsbin for this, but this description and the code below should suffice.

```
  <paper-dialog heading="{content.title}}" class="scrolling" transition="core-transition-center">   
     <template repeat="{{ item in content.items }}">
        // code removed for brevity
    </template>
</paper-dialog> 
```

_Copied from original issue: Polymer/polymer#1090_

**Comment by tjsavage** [comment]
_From @davidmaxwaterman on January 14, 2015 2:43_

probably not relevant but looks like you're missing a '{' - might want to edit that (then I'll delete this comment), so it's not distracting the reader.
also, shouldn't this be file on paper-dialog? It's not related to polymer itself, is it? https://github.com/Polymer/paper-dialog/issues

**Comment by tjsavage** [comment]
_From @KrisSiegel on March 4, 2015 2:41_

I'm having a similar issue and I think it's related to https://github.com/Polymer/paper-dialog/issues/44.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.

**Comment by tjsavage** [comment]
_From @KrisSiegel on October 25, 2015 8:1_

Does anyone know if this was addressed? I haven't used Polymer in some time now but I'd like to know if it was.

**Comment by tjsavage** [comment]
_From @rvraaphorst on November 11, 2015 11:8_

Seems like this issue is still there in 1.0

**Comment by NamTThai** [comment]
+1 this issue is pretty annoying and I have to resort to this workaround:

```
var dialog = this.$.dialog;
      dialog.open();
      dialog.addEventListener("iron-overlay-opened", function() {
        dialog.center();
        dialog.removeEventListener("iron-overlay-opened");
});
```

**Comment by valdrinkoshi** [comment]
Could not reproduce with `v1.0.3` http://jsbin.com/gefuci/edit?html,output

**Comment by NamTThai** [comment]
@valdrinkoshi try this, just open it a couple of times and you'll see what we're talking about: http://jsbin.com/yofidoguca/edit?html,output

**Comment by valdrinkoshi** [comment]
Oh nice! :D reopening, will have a closer look!

**Comment by zoechi** [comment]
If the content changes the dialog needs to be notified

``` js
            this.$.dialog.toggle();
            if(this.$.dialog.opened) {
              this.async(function () {
                this.$.dialog.notifyResize();
              });
            }
```

**Comment by NamTThai** [comment]
Oh nice! I tried `notifyResize()` before but didn't know that it's supposed to be wrapped in `async()`. Thanks!

**Comment by davidmaxwaterman** [comment]
I wonder what the rationale is for the use of async().

**Comment by zoechi** [comment]
I just tried it and without `async` it didn't work. I assume the content of the dialog wasn't rendered yet and therefore the correct size couldn't be calculated.

**Comment by davidmaxwaterman** [comment]
that makes total sense, thanks.

**Comment by NamTThai** [comment]
Async is super useful but a lot of my colleague don't know about it. My mentality is mostly like hm-this-bug-is-kinda-weird-maybe-async-will-fix-it-yep-id-did-yey kinda mindset. Would be great if there's an in depth documentation about async in API Guide

**Comment by valdrinkoshi** [comment]
`async` is basically like using timeouts. You shouldn't need to do `notifyResize()`, I believe this should be handled by the dialog.

**Comment by jptrainor** [comment]
It is still broken.  If I make a simple dialog with a short message then it is offset to the left.  The element.style has a left fixed positionsthat is wrong. 

For example:

```
<paper-dialog id="shortMessageNotCentered" modal>
      <paper-dialog-scrollable>
        <p>this is not centered</p>
      </paper-dialog-scrollable>
</paper-dialog>
```

 However, if the message is long, and spans multiple lines then the dialog is centered correctly:

```
<paper-dialog id="longMessageIsCentered" modal>
      <paper-dialog-scrollable>
        <p>This is centered correctly. The incorrect centering in the shorter case seems to be related to the small amount of content that exists in that dialog because the position of the dialog that contains this run on sentence is perfect.</p>
      </paper-dialog-scrollable>
</paper-dialog>
```

I tried notifyResize() but it made no difference. I worked around the problem with a custom css style that is applied **only** to the dialog with the short message. Don't apply this to a dialog with long messages because it messes up their width - they end up too narrow. (It's just a work around... I haven't looked into why the latter happens.)

```
    .workAroundSmallContentDialogCentering {
      margin: 0;
      position: absolute;
      left: 50%;
      top: 50%;
      transform: translate(-50%, -50%);
    }

  <paper-dialog class="workAroundSmallContentDialogCentering"> ...

```

**Comment by valdrinkoshi** [comment]
Will verify this.
Anyways I think it is an edge case to use `paper-dialog-scrollable` for something that doesn't need scrolling.
You could set a `min-width` and `min-height` to `paper-dialog-scrollable`

**Comment by valdrinkoshi** [comment]
@jptrainor could not reproduce the issue http://jsbin.com/gitodet/2/edit?html,output
Make sure you update your bower dependencies to get the latest releases of the elements ;)

**Comment by jptrainor** [comment]
Thanks for looking at it.

For reference, here is what I have in my bower.json

   "iron-elements": "PolymerElements/iron-elements#1.0.8",
    "paper-elements": "PolymerElements/paper-elements#1.0.7",

.. and I currently (before updating) see these versions:

sandpiper:WbmPolymerClient jpt$ bower list | grep dialog
│ ├─┬ paper-dialog#1.0.4
│ │ ├─┬ paper-dialog-behavior#1.2.0
│ ├─┬ paper-dialog-behavior#1.2.0 (1.2.1 available)
│ ├─┬ paper-dialog-scrollable#1.1.1 (1.1.4 available)
sandpiper:WbmPolymerClient jpt$ bower list | grep webcomponents
│ │   └── webcomponentsjs#0.7.21

I'll update and post back with the outcome.

**Comment by jptrainor** [comment]
My elements are up to date.  That wasn't the problem.  But I made some progress with it:

I encountered this problem once again while testing my Polymer app using the Android 4.4 WebView on an emulator.  Everything was fine except that once again the dialog was not centerer.  This dialog is displayed at page load time.  I could see in the emulator that the paper-drawer-panel was mid-way through its closing animation at the same moment the dialog was displayed.  If I hide the drawer panel before opening this dialog then the problem is resolved (no custome css needed, as mentioned in my prior post). This sort of dynamic interaction with other elements may be at the root of the problems that other have also reported.

**Comment by valdrinkoshi** [comment]
Interesting, it depends also from the structure of your Dom, where you declare the dialog. It would be helpful to have a jsbin to see the issue :)
Also, if you see the problem in the emulator but not in the real device, that might not be worth to fix.

**Comment by nicholaswmin** [comment]
This is not a problem in the emulator - I'm seeing this in Chrome for the past 4 months now.

I'm guessing the `<paper-dialog>` is positioned via JS. If that's the case, does this positioning system take any notifications when it's resized - i.e dynamic content was added to it?

**Comment by valdrinkoshi** [comment]
Yes, positioning and fitting is done by `iron-fit-behavior`. In addition, `iron-overlay-behavior` will observe node changes (aka additions/deletions) and call the `refit()` method will compute again positioning and fitting. It will do the same if an `iron-resize` event is fired by itself or by one of the children. If you resize the dialog by adding a class or modifying its style, you're also responsible to notify it that it needs to be resized by calling `dialog.notifyResize()` or by firing a `iron-resize` event.

**Comment by nicholaswmin** [comment]
Okay so just to clear things up.

My `<paper-dialog>` is resized because content was added to it, in my case because a `<dom-repeat>` rendered additional elements to it.

The resize in my case happens because of dynamically added content, not because of any explicit class or style declarations.

Therefore it should resize itself automatically.

**Comment by valdrinkoshi** [comment]
Here a working example with `dom-repeat` http://jsbin.com/gimajew/1/edit?html,output

**Comment by nicholaswmin** [comment]
Hm, that's a bit strange.

Could it be the position of my dialog in the DOM Tree? - I'll investigate and let you know.

Thanks a lot,

**Comment by ubbeK** [comment]
> Here a working example with dom-repeat http://jsbin.com/gimajew/1/edit?html,output

Is it possible to add an animation for a smoother resize?

**Comment by valdrinkoshi** [comment]
Sure @ubbeK, you can create your custom element to do that for you, see this example http://jsbin.com/misuke/1/edit?html,output
Few things to notice:
- we have a wrapper that uses `display: flex` to center its content (the `paper-dialog` in this case)
- we disable the positioning calculations of `iron-fit-behavior` by setting `position: fixed` to `paper-dialog`
- we use an animation for each row which animates the height (you could create a custom element for it as well if you want)

#usetheplatform :)

**Comment by ubbeK** [comment]
@valdrinkoshi Thanks a lot!

**Comment by davidmaxwaterman** [comment]
Personally, I don't find the 'solution' for animating the to be particularly satisfactory. "Using the platform" is all very well, but this does seem to be something the user of the element would expect without having to go to all the effort of wrapping the element and such (which I'm having particular difficulty with). After all, it already animates when opened and closed.
