### ISSUE TITLE
Multiple modal dialogs on screen throw 'Maximum call stack size exceeded' errors

### ISSUE THREAD

**Issue by TheMoonDawg** [PolymerElements/paper-dialog#69]
We have two separate paper-dialog windows and occasionally open them both at the same time. Whenever we focus on the topmost dialog, several errors are thrown as shown below.

![error](https://cloud.githubusercontent.com/assets/7232302/11187621/c2fcfa26-8c4c-11e5-951f-35b7b17dcbc0.png)

We found this to only happen when both of the dialogs have the 'modal' attribute. Removing that attribute prevented the errors from being thrown, but we need it as a modal for our program.

Is this a known issue? Thanks!

Paper-Dialog Version 1.0.2
Google Chrome Version 46.0.2490.86 m

**Comment by yonathan9669** [comment]
I'm getting exactly the same error, it shows up when a 2nd dialog it's opened over a currently opened one.
<img width="673" alt="screen shot 2015-11-25 at 3 25 55 p m" src="https://cloud.githubusercontent.com/assets/897389/11408051/cf726df2-9388-11e5-9e67-fd2487a6b8ef.png">

It's been thrown just by clicking anywhere inside the dialog.

And I'm getting another error before it. Something about a null object when trying to set an event I believe.

**Comment by bendavis78** [comment]
@MoonDawg92 are you able to get multiple modal dialogs to work correctly (besides having this issue)? For me the backdrop [only appears beneath the first dialog](http://jsbin.com/taxoli/47/edit?html,output). I've created [another issue](https://github.com/PolymerElements/iron-overlay-behavior/issues/58) in `iron-overlay-behavior` for that.

**Comment by bendavis78** [comment]
Also, in case anyone needs to reproduce the maximum call stack error: http://jsbin.com/taxoli/52/edit?html,output

**Comment by TheMoonDawg** [comment]
@bendavis78 I also have that issue. The backdrop only shows beneath the first dialog.

Since that's more of an aesthetic issue (although important), I didn't bother mentioning it. I can worry about making it pretty after it stops crashing. :)

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/paper-dialog-behavior#46
