### ISSUE TITLE
Wrong version dependency

### ISSUE THREAD

**Issue by ckuiawa** [PolymerElements/paper-dialog#72]
Paper-dialog version 1.0.3 has a bower dependency on paper-dialog-behavior of ~1.0.0.  That means it's going to get only the latest 1.0.x version.  However, in version 1.0.3, paper-dialog is loading paper-dialog-shared-styles.html, which only exists in paper-dialog 1.1.0.

Chrome will let the import of paper-dialog-shared-styles.html fail and keep loading the page.  Firefox stops loading the element when that import fails.

**Comment by ebidel** [comment]
You mean it only exists in [paper-dialog-behavior 1.1.0](https://github.com/PolymerElements/paper-dialog-behavior/tree/v1.1.0), right?

paper-dialog 1.0.3 [depends on](https://github.com/PolymerElements/paper-dialog/blob/v1.0.3/bower.json#L23) `paper-dialog-behavior#^1.0.0` (not the `^` and not `~`), which will get you minor updates of the paper-dialog-behavior. 

A good tool for checking the upgrade path is: http://jubianchi.github.io/semver-check/. If you put in `^1.0.0` in the first box and `1.1.0` in the second, you'll see that 1.1.0 matches.

**Comment by ckuiawa** [comment]
Yes, I meant only exists in paper-dialog-behavior 1.1.0.  
And yes, you are correct about ^ vs. ~.  
The problem ended up being I have an element that depended on ~1.0.0 of paper-dialog and ~1.0.0 of paper-dialog-behavior.  Bower resolved that as 1.0.3 of paper-dialog and 1.0.6 of paper-dialog-behavior.  Those 2 are not compatible.  While using ^1.0.0, 1.1.0 does satisfy the constraint, 1.0.6 also satisfies it but should not.

**Comment by valdrinkoshi** [comment]
Hi @ckuiawa, have you tried to set the element dependency to `paper-dialog-behavior#^1.0.0` and `paper-dialog#^1.0.0` (`^` instead of `~`) ?
