### ISSUE TITLE
MMMoooaaarrr style for paper-dialog-button

### ISSUE THREAD

**Issue by GeoloeG-IsT** [PolymerElements/paper-dialog#76]
Hi,
currently, it is only possible to apply a custom property to the buttons of a dialog via `--paper-dialog-button-color`.
It would be nice either to have an additional custom property for the background like `--paper-dialog-button-background-color` or better a more general mixin like `--paper-dialog-button`.
Cheers,
Pascal

**Comment by GeoloeG-IsT** [comment]
Concerns paper-dialog-behavior... Closing here...

**Comment by niesmo** [comment]
BTW, here is the link to the issue in the paper-dialog-behavior https://github.com/PolymerElements/paper-dialog-behavior/issues/49
