### ISSUE TITLE
Press ESC can close modal-dialog

### ISSUE THREAD

**Issue by khoanguyenlio** [PolymerElements/paper-dialog#78]
With modal-dialog i thought only button have  dialog-confirm can close modal but ESC button can close too. It's bug or design????

**Comment by amandeepmittal** [comment]
@khoanguyenlio 
It is designed that way. Before it was browser dependent, for example, browsers like Google Chrome and Firefox would support but these days it seem most browsers support this feature.

**Comment by khoanguyenlio** [comment]
so.... i should cover that case with binding keyup or something if i dont want to press ESC to close modal???

**Comment by amandeepmittal** [comment]
@khoanguyenlio yes you can. Mention a separate key in your code, but I am not that use of Escape can be avoided in all browsers.

**Comment by khoanguyenlio** [comment]
ok Thank you! <3

**Comment by amandeepmittal** [comment]
you are welcome!

**Comment by valdrinkoshi** [comment]
You can also set the [`noCancelOnEscKey`](https://elements.polymer-project.org/elements/paper-dialog#noCancelOnEscKey) property to block the closing

``` html
<paper-dialog modal no-cancel-on-esc-key> </paper-dialog>
```

http://jsbin.com/zumonizafo/edit?html,output

**Comment by khoanguyenlio** [comment]
NICE! Thank you <3
