### ISSUE TITLE
Dialog not closing on Android Back

### ISSUE THREAD

**Issue by locomuco** [PolymerElements/paper-dialog#89]
In case of a 'back' button event of the Android action bar, I would expect the dialog to be closed.

**Comment by Oupsla** [comment]
@locomuco do you find a solution to handle the "back" button ?

**Comment by locomuco** [comment]
@Oupsla no didn't follow up...

**Comment by valdrinkoshi** [comment]
You can listen to the [`popstate` event](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate) and close any opened dialog in there

**Comment by Oupsla** [comment]
@valdrinkoshi do you think it would possible (when the popstate event is triggered) to just close the paper-dialog instead of going back ?

Or a workaround would be to change the route when the paper-dialog is opened (or closed) ?

**Comment by valdrinkoshi** [comment]
The back button triggers browser back, and that cannot be silently blocked. You could `history.pushState()` when opening the dialog, and on close it on popstate (aka on back button). See more details here https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method

**Comment by Oupsla** [comment]
@valdrinkoshi  Thanks, I will try this !
Little question : could this be implemented directly in paper-dialog (or in iron-overlay-behavior) with an extra parameter or it is better to implement it outside (in apps) ?

**Comment by valdrinkoshi** [comment]
paper-dialog should not interfere with the history state, as what should be pushed in the history is opinionated, that's business logic.

**Comment by Oupsla** [comment]
Working really great, thanks @valdrinkoshi !

For information for future users : 

- When opening the paper-dialog, call `history.pushState` and add a listener to `window.onpopstate`
- This listener will close the paper-dialog and clear the listener (just make `window.onpopstate = null`)
- If the user close the paper-dialog "normally", just clear the listener and make a `history.back()` to retrieve previous history state
