### ISSUE TITLE
paper-dialog looks blurry on Android Browser

### ISSUE THREAD

**Issue by RobinLinus** [PolymerElements/paper-dialog#90]
The `paper-dialog` looks very blurry on Android Browser "Internet" Version 1.5.28.  [Screenshot](https://snapdrop.net/images/AkwXAllGoRmpA6k4n_wQICPI15wC92_j9aWrlEfY2rg7.jpg)
The bug can be reproduced [here](http://snapdrop.net) by sending a file to the "Internet" browser.

**Comment by valdrinkoshi** [comment]
Hi @capira12, Android Browser is not supported, Chrome for Android is supported.
https://www.polymer-project.org/1.0/resources/compatibility.html
