### ISSUE TITLE
Model dialog not keeping focus when using <tab> <shift-tab>

### ISSUE THREAD

**Issue by togiles** [PolymerElements/paper-dialog#92]
See Issue #63 for initial report, I'm still able to reproduce:

http://embed.plnkr.co/VPNA4xvZWFtL3O1vPRVe/

Open the dialog and click <tab> and / or <shift-tab> and you'll see the paper-input items get selected below the modal dialog.

**Comment by valdrinkoshi** [comment]
Can't reproduce here http://jsbin.com/hemowo/2/edit?html,output
Please make sure you update your dependencies and get the latests releases of `iron-overlay-behavior, paper-dialog-behavior, paper-dialog`.

**Comment by togiles** [comment]
Strange, I thought I was pulling the latest:

```
 <script src="https://cdn.rawgit.com/download/polymer-cdn/master/lib/webcomponentsjs/webcomponents-lite.js"></script>
    <link rel="import" href="https://cdn.rawgit.com/download/polymer-cdn/master/lib/paper-button/paper-button.html">
    <link rel="import" href="https://cdn.rawgit.com/download/polymer-cdn/master/lib/paper-dialog/paper-dialog.html">
    <link rel="import" href="https://cdn.rawgit.com/download/polymer-cdn/master/lib/paper-input/paper-input.html">
```

Where are the "latest releases"?  (fairly new to polymer so pardon my ignorance)

**Comment by valdrinkoshi** [comment]
For your jsbins/snippets it's better to rely on `polygit` to get the latest & greatest versions. You'll find more details here http://polygit.org ;)
