### ISSUE TITLE
exit-animation problem

### ISSUE THREAD

**Issue by lp177** [PolymerElements/paper-dialog#93]
Have you already try to create a button for open a paper-dialog with enter and exit attributes for neon-animations and try to click several time with an interval most short than your exit animation duration on this button ?

After that, this paper-dialog seem to be unusable, it can't not remain open.

Context:

Polymer 1.2.3
paper-dialog 1.0.3
neon-animation 1.0.9

**Comment by valdrinkoshi** [comment]
Hi @lp177, this has been fixed in `paper-dialog v1.0.4`, please update your dependencies and see if the problem persists & let us know :)

**Comment by lp177** [comment]
Well seen, this.cancelAnimation(); line 95/103, thank you very much.
