### ISSUE TITLE
Rendering issue for scrolling dialog in IE11 on Win7

### ISSUE THREAD

**Issue by rictic** [PolymerElements/paper-dialog#94]
If you use IE 11 on Windows 7, go to [the demo site](https://elements.polymer-project.org/elements/paper-dialog?view=demo:demo/index.html&active=paper-dialog), and open the scrolling dialog, it's weirdly skinny.

**Comment by rictic** [comment]
Filed as P0 as this is causing problems for the share dialog in Play Music.

**Comment by valdrinkoshi** [comment]
It seems IE11 doesn't like `position: fixed` on the container of `paper-scrollable` , while Chrome and other browsers handle it correctly http://jsbin.com/pobigu/6/edit
IE11
![screen shot 2016-03-11 at 4 48 56 pm](https://cloud.githubusercontent.com/assets/6173664/13719359/3c56bc7e-e7a9-11e5-9a03-a21320ba0a72.png)
Chrome
<img width="1000" alt="screen shot 2016-03-11 at 4 49 17 pm" src="https://cloud.githubusercontent.com/assets/6173664/13719364/468a927e-e7a9-11e5-954c-3c839c9e629f.png">

@notwaldorf, have you already seen something like this with `iron-flex-layout`?

**Comment by santosborom** [comment]
I have observed this with IE11 on Windows 10. The scrollable dialog is "narrowed".

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/paper-dialog-scrollable#40
