### ISSUE TITLE
paper-dialog broken in Firefox 47

### ISSUE THREAD

**Issue by ghost** [PolymerElements/paper-dialog#95]
Steps to reproduce:

1.open https://elements.polymer-project.org/elements/paper-dialog?view=demo:demo/index.html&active=paper-dialog
2. click on Transitions

dialog will not show up and this error will show up in the console: "NotSupportedError: Animation with a target not bound to a document is not yet supported."

I am using Firefox Developer Edition 47.0a2

**Comment by valdrinkoshi** [comment]
Confirmed, I see the same error on Firefox Developer Edition 47.0a2 on mac os. This probably needs to be moved to `neon-animation` repo. 
@dstockwell any ideas?

**Comment by dstoc** [comment]
Firefox is shipping an incomplete implementation of Web Animations in Developer Edition. This does **not** reflect the behavior that will be present in their beta/stable channels. See https://github.com/web-animations/web-animations-js/issues/66#issuecomment-196597767

**Comment by valdrinkoshi** [comment]
Cool, closing this then!
