### ISSUE TITLE
Custom Polymer Element (using PaperDialog behavior) gets in bad render state when open/close animation plays at same time.

### ISSUE THREAD

**Issue by mccreavy** [PolymerElements/paper-dialog#99]
### Expected outcome

If polymer element's ["opened"] attribute is true, the element should be visible on screen regardless of state-change during animation.
### Observed outcome

Polymer element's ["opened"] attribute is true, but the element is not visible on screen.

### Live Demo

http://jsbin.com/fusijafeno/1/edit?html,output
### Steps to reproduce

See jsbin for steps along these lines:
1. Click "Show" button to show "big blue" polymer element.
2. Click page background to see expected "close" behavior of element.
3. Click "Show" again to reshow polymer element
4. Click "Show" again -- there are now two events (hide due to default behavior, and show due to show) happening in quick succession.
5. Now the "sj-mini-queue" element is not visible on screen, but its "opened" attribute is true.

-->
### Browsers Affected

- [ x] Chrome
  (no other versions tested)

**Comment by valdrinkoshi** [comment]
You should cancel the previous animation before triggering a new one, like it is done in `paper-dialog` https://github.com/PolymerElements/paper-dialog/blob/master/paper-dialog.html#L94

**Comment by mccreavy** [comment]
Thanks, much appreciated!
